In [1]:
RUN_TARGET = "local"  # "colab" | "local"

## Setup Instructions

### Running on Google Colab
1. Set `RUN_TARGET = "colab"` in Cell 1.
2. Run the install cell and restart if requested.
3. Mount Drive if you want to read synced `models/` and `results/` artifacts.
4. Run the remaining cells top to bottom.

### Running locally
1. Keep `RUN_TARGET = "local"`.
2. The notebook scans the local `models/` and `results/` folders.
3. It loads saved probe artifacts and renders main-paper and supplementary figures without retraining or reprobe computation.

In [2]:
if RUN_TARGET == "colab":
    import importlib.metadata as _md
    import subprocess as _sp
    import sys as _sys

    _required = {
        "numpy": "1.26.4",
        "scipy": "1.15.3",
        "scikit-learn": "1.8.0",
        "transformers": "4.48.1",
        "huggingface-hub": "0.36.2",
        "statsmodels": "0.14.5",
        "seaborn": "0.13.2",
    }

    def _version_matches(name: str, expected: str) -> bool:
        try:
            return _md.version(name) == expected
        except _md.PackageNotFoundError:
            return False

    _missing_or_mismatched = [
        f"{name}=={version}"
        for name, version in _required.items()
        if not _version_matches(name, version)
    ]

    if _missing_or_mismatched:
        print("Installing:", ", ".join(_missing_or_mismatched))
        _sp.run([
            _sys.executable,
            "-m",
            "pip",
            "install",
            "-q",
            "--upgrade",
            *_missing_or_mismatched,
        ], check=True)
        raise SystemExit(
            "Colab environment updated. Restart the runtime once, then rerun the notebook from the top."
        )
    else:
        print("Colab environment already compatible. No reinstall needed.")
else:
    print("Local environment detected. Skipping Colab setup.")

Local environment detected. Skipping Colab setup.

In [3]:
if RUN_TARGET == "colab":
    from google.colab import drive as _drive
    from pathlib import Path

    _drive.mount("/content/drive", force_remount=False)
    DRIVE_ROOT = Path("/content/drive/MyDrive/XAllergen2.0")
    DRIVE_MODELS = DRIVE_ROOT / "models"
    DRIVE_RESULTS = DRIVE_ROOT / "results"
    print(f"Google Drive mounted: {DRIVE_ROOT}")
else:
    print("Local run: skipping Google Drive mount.")

Local run: skipping Google Drive mount.

# 08 - Cross-Model Probe Visualisation

This notebook is the centralized visualization layer for probe outputs that already exist in `results/`. It does not load models or generate attribution scores; it only discovers saved probe-row CSVs, combines them, and renders main-paper plus supplementary figures.

In [4]:
import sys
from pathlib import Path

# Allow imports from the src-layout package without a root-level shim.
for _candidate in [Path.cwd(), *Path.cwd().parents]:
    _src_dir = _candidate / "src"
    if (_src_dir / "xallergen").exists() and str(_src_dir) not in sys.path:
        sys.path.insert(0, str(_src_dir))
        break
import importlib

if RUN_TARGET == "colab":
    RUNTIME_ROOT = Path("/content/XAllergen2.0")
    if str(RUNTIME_ROOT) not in sys.path:
        sys.path.insert(0, str(RUNTIME_ROOT))
    _SRC_DIR = RUNTIME_ROOT / "src"
    if _SRC_DIR.exists() and str(_SRC_DIR) not in sys.path:
        sys.path.insert(0, str(_SRC_DIR))

import xallergen.baseline_notebook_utils as baseline_notebook_utils
import xallergen.mtl_epitope_notebook_utils as mtl_epitope_notebook_utils

importlib.reload(baseline_notebook_utils)
importlib.reload(mtl_epitope_notebook_utils)

from xallergen.baseline_notebook_utils import configure_matplotlib_cache, detect_device, find_project_root, print_runtime_context
from xallergen.mtl_epitope_notebook_utils import discover_probe_row_artifacts, load_available_probe_rows, render_probe_figures_from_rows, save_combined_probe_tables

if RUN_TARGET != "colab":
    configure_matplotlib_cache(Path.cwd())

import pandas as pd

/Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
if RUN_TARGET == "colab":
    PROJECT_ROOT = RUNTIME_ROOT
    MODELS_DIR = DRIVE_MODELS if DRIVE_MODELS.exists() else PROJECT_ROOT / "models"
    RESULTS_DIR = DRIVE_RESULTS if DRIVE_RESULTS.exists() else PROJECT_ROOT / "results"
    print(f"Using models dir: {MODELS_DIR}")
    print(f"Using results dir: {RESULTS_DIR}")
else:
    PROJECT_ROOT = find_project_root(Path.cwd())
    DEVICE = detect_device()
    print_runtime_context(DEVICE, PROJECT_ROOT)
    MODELS_DIR = PROJECT_ROOT / "models"
    RESULTS_DIR = PROJECT_ROOT / "results"

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

RUN_TARGET: local
Device: mps
Project root: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0
GPU configuration:
  backend: Apple Metal Performance Shaders (MPS)
  built with MPS: True
  MPS available: True

## Discover Available Variants

Each compatible checkpoint in `models/` is mapped to the probe-row CSV that should already exist in `results/`. If a probe artifact is missing, this notebook skips that model rather than recomputing it. Use `07_generate_probe_rows.ipynb` to generate or refresh missing probe artifacts first.

In [6]:
discovery_df = discover_probe_row_artifacts(MODELS_DIR, RESULTS_DIR)
discovery_df

,checkpoint_name,variant,model_family,checkpoint_path,probe_rows_path,probe_rows_exists
0,baseline_frozen_esm2.pt,baseline,Baseline (04),/Users/jianzhouyao/Library/Mobile Documents/co...,/Users/jianzhouyao/Library/Mobile Documents/co...,True
1,mtl_frozen_esm2_epitope.pt,frozen,MTL (05 frozen),/Users/jianzhouyao/Library/Mobile Documents/co...,/Users/jianzhouyao/Library/Mobile Documents/co...,True
2,mtl_top1_unfrozen_esm2_epitope.pt,top1_unfrozen,MTL (06 top1_unfrozen),/Users/jianzhouyao/Library/Mobile Documents/co...,/Users/jianzhouyao/Library/Mobile Documents/co...,True

In [7]:
all_probe_df = load_available_probe_rows(discovery_df)
all_probe_df.head()

,accession,seq_len,epitope_density,n_epitope_residues,model_family,method,label_variant,auroc,auprc,precision_at_k,source_probe_rows_path
0,A0A834K244,251,0.549801,138,Baseline (04),attention_weights,original,0.630242,0.621814,0.623188,/Users/jianzhouyao/Library/Mobile Documents/co...
1,A0A834K244,251,0.549801,138,Baseline (04),attention_weights,scrambled,0.491920,0.547467,0.543478,/Users/jianzhouyao/Library/Mobile Documents/co...
2,A0A834K244,251,0.549801,138,Baseline (04),integrated_gradients,original,0.474349,0.535056,0.492754,/Users/jianzhouyao/Library/Mobile Documents/co...
3,A0A834K244,251,0.549801,138,Baseline (04),integrated_gradients,scrambled,0.505130,0.569623,0.550725,/Users/jianzhouyao/Library/Mobile Documents/co...
4,A0A834K244,251,0.549801,138,Baseline (04),gradient_x_input,original,0.488906,0.539134,0.543478,/Users/jianzhouyao/Library/Mobile Documents/co...

## Save Combined Tables

These artifacts provide a single reusable row-wise table plus bootstrap-CI summaries across all available families. Figures can be regenerated later from `all_models_probing_rows.csv` without rerunning training or probing.

In [8]:
table_outputs = save_combined_probe_tables(all_probe_df, RESULTS_DIR)
MULTI_MODEL_ROWS_CSV = table_outputs["rows_path"]
MULTI_MODEL_SUMMARY_CSV = table_outputs["summary_path"]
summary_df = table_outputs["summary_df"]
summary_df

Saved main localization summary to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/probing/summaries/main_localization_summary.csv
Saved supplementary all-signals summary to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/probing/summaries/supplementary_all_signals_summary.csv
Saved label-scrambling summary to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/probing/summaries/probe_summary_with_scrambling.csv

,model_family,method,label_variant,method_category,auroc_mean,auroc_ci_low,auroc_ci_high,auprc_mean,auprc_ci_low,auprc_ci_high,precision_at_k_mean,precision_at_k_ci_low,precision_at_k_ci_high,n_proteins
0,Baseline (04),random_mean,original,Null baseline,0.5011,0.4993,0.5029,0.2697,0.2222,0.3226,0.2517,0.2041,0.3044,58
1,Baseline (04),random_mean,scrambled,Null baseline,0.5004,0.4990,0.5019,0.2690,0.2220,0.3219,0.2515,0.2039,0.3044,58
2,Baseline (04),attention_weights,original,Model-internal signal,0.4438,0.4151,0.4752,0.2468,0.1985,0.3008,0.2131,0.1622,0.2703,58
3,Baseline (04),attention_weights,scrambled,Model-internal signal,0.5172,0.5011,0.5332,0.2778,0.2317,0.3267,0.2618,0.2153,0.3130,58
4,Baseline (04),integrated_gradients,original,Post-hoc attribution,0.4328,0.3932,0.4772,0.2550,0.2046,0.3103,0.2189,0.1633,0.2776,58
5,Baseline (04),integrated_gradients,scrambled,Post-hoc attribution,0.4974,0.4821,0.5115,0.2653,0.2195,0.3161,0.2510,0.2013,0.3056,58
6,Baseline (04),gradient_x_input,original,Post-hoc attribution,0.4627,0.4411,0.4862,0.2572,0.2106,0.3096,0.2465,0.1964,0.3023,58
7,Baseline (04),gradient_x_input,scrambled,Post-hoc attribution,0.5023,0.4850,0.5195,0.2750,0.2261,0.3280,0.2482,0.1990,0.3016,58
8,Baseline (04),smoothgrad_ig,original,Post-hoc attribution,0.4330,0.3929,0.4771,0.2548,0.2045,0.3102,0.2198,0.1636,0.2788,58
9,Baseline (04),smoothgrad_ig,scrambled,Post-hoc attribution,0.5036,0.4848,0.5215,0.2670,0.2182,0.3221,0.2523,0.2029,0.3085,58
10,Baseline (04),occlusion,original,Perturbation sensitivity,0.4959,0.4751,0.5164,0.2669,0.2198,0.3185,0.2397,0.1903,0.2949,58
11,Baseline (04),occlusion,scrambled,Perturbation sensitivity,0.4999,0.4867,0.5152,0.2673,0.2164,0.3229,0.2483,0.1934,0.3064,58
12,MTL (05 frozen),random_mean,original,Null baseline,0.5011,0.4993,0.5029,0.2697,0.2222,0.3226,0.2517,0.2041,0.3044,58
13,MTL (05 frozen),random_mean,scrambled,Null baseline,0.5004,0.4990,0.5019,0.2690,0.2220,0.3219,0.2515,0.2039,0.3044,58
14,MTL (05 frozen),attention_weights,original,Model-internal signal,0.4478,0.4211,0.4774,0.2462,0.1983,0.2990,0.2126,0.1615,0.2699,58
15,MTL (05 frozen),attention_weights,scrambled,Model-internal signal,0.4997,0.4869,0.5129,0.2667,0.2178,0.3195,0.2483,0.1958,0.3024,58
16,MTL (05 frozen),integrated_gradients,original,Post-hoc attribution,0.4434,0.4022,0.4886,0.2583,0.2075,0.3142,0.2218,0.1654,0.2821,58
17,MTL (05 frozen),integrated_gradients,scrambled,Post-hoc attribution,0.4920,0.4811,0.5025,0.2675,0.2206,0.3204,0.2453,0.1953,0.3003,58
18,MTL (05 frozen),gradient_x_input,original,Post-hoc attribution,0.4746,0.4528,0.4984,0.2618,0.2155,0.3139,0.2515,0.2004,0.3080,58
19,MTL (05 frozen),gradient_x_input,scrambled,Post-hoc attribution,0.5063,0.4922,0.5206,0.2710,0.2238,0.3229,0.2546,0.2075,0.3066,58
20,MTL (05 frozen),smoothgrad_ig,original,Post-hoc attribution,0.4435,0.4022,0.4888,0.2587,0.2079,0.3147,0.2234,0.1679,0.2831,58
21,MTL (05 frozen),smoothgrad_ig,scrambled,Post-hoc attribution,0.4921,0.4771,0.5067,0.2643,0.2156,0.3174,0.2485,0.1985,0.3025,58
22,MTL (05 frozen),occlusion,original,Perturbation sensitivity,0.4943,0.4748,0.5132,0.2691,0.2222,0.3210,0.2398,0.1910,0.2922,58
23,MTL (05 frozen),occlusion,scrambled,Perturbation sensitivity,0.5024,0.4896,0.5148,0.2708,0.2228,0.3235,0.2584,0.2082,0.3095,58
24,MTL (05 frozen),residue_head,original,Supervised residue predictor,0.6495,0.6047,0.6882,0.3735,0.3099,0.4416,0.3378,0.2723,0.4051,58
25,MTL (05 frozen),residue_head,scrambled,Supervised residue predictor,0.4929,0.4778,0.5070,0.2652,0.2165,0.3190,0.2479,0.1955,0.3028,58
26,MTL (06 top1_unfrozen),random_mean,original,Null baseline,0.5011,0.4993,0.5029,0.2697,0.2222,0.3226,0.2517,0.2041,0.3044,58
27,MTL (06 top1_unfrozen),random_mean,scrambled,Null baseline,0.5004,0.4990,0.5019,0.2690,0.2220,0.3219,0.2515,0.2039,0.3044,58
28,MTL (06 top1_unfrozen),attention_weights,original,Model-internal signal,0.4477,0.4202,0.4783,0.2467,0.1988,0.2999,0.2140,0.1623,0.2719,58
29,MTL (06 top1_unfrozen),attention_weights,scrambled,Model-internal signal,0.4980,0.4847,0.5113,0.2663,0.2174,0.3194,0.2484,0.1962,0.3030,58
30,MTL (06 top1_unfrozen),integrated_gradients,original,Post-hoc attribution,0.4475,0.4059,0.4923,0.2589,0.2083,0.3147,0.2226,0.1663,0.2827,58
31,MTL (06 top1_unfrozen),integrated_gradients,scrambled,Post-hoc attribution,0.4912,0.4808,0.5015,0.2669,0.2202,0.3199,0.2431,0.1941,0.2977,58
32,MTL (06 top1_unfrozen),gradient_x_input,original,Post-hoc attribution,0.4804,0.4606,0.5033,0.2643,0.2167,0.3168,0.2545,0.2041,0.3106,58
33,MTL (06 top1_unfrozen),gradient_x_input,scrambled,Post-hoc attribution,0.5065,0.4923,0.5210,0.2693,0.2222,0.3210,0.2561,0.2113,0.3079,58
34,MTL (06 top1_unfrozen),smoothgrad_ig,original,Post-hoc attribution,0.4481,0.4063,0.4932,0.2590,0.2086,0.3146,0.2247,0.1693,0.2845,58
35,MTL (06 top1_unfrozen),smoothgrad_ig,scrambled,Post-hoc attribution,0.4924,0.4777,0.5064,0.2650,0.2158,0.3187,0.2479,0.1978,0.3017,58
36,MTL (06 top1_unfrozen),occlusion,original,Perturbation sensitivity,0.4936,0.4729,0.5133,0.2699,0.2221,0.3213,0.2396,0.1903,0.2945,58
37,MTL (06 top1_unfrozen),occlusion,scrambled,Perturbation sensitivity,0.5045,0.4892,0.5186,0.2726,0.2247,0.3244,0.2615,0.2098,0.3143,58
38,MTL (06 top1_unfrozen),residue_head,original,Supervised residue predictor,0.6368,0.5979,0.6740,0.3580,0.2974,0.4236,0.3228,0.2644,0.3865,58
39,MTL (06 top1_unfrozen),residue_head,scrambled,Supervised residue predictor,0.4945,0.4779,0.5102,0.2646,0.2160,0.3177,0.2436,0.1912,0.2988,58

## Plot All Available Families

In [9]:
figure_outputs = render_probe_figures_from_rows(all_probe_df, RESULTS_DIR)
figure_outputs

Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main/main_localization_auroc.png
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main/main_localization_auroc.pdf
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main/main_localization_auprc.png
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main/main_localization_auprc.pdf
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main/main_localization_precision_at_k.png
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main/main_localization_precision_at_k.pdf

Main figure caption draft:
We compare a null random baseline, post-hoc protein-level explanations (Integrated Gradients and occlusion sensitivity), and a supervised MTL residue-level epitope head. Metrics are computed per protein against IEDB epitope annotations and averaged across proteins. Attention-pooling weights and additional gradient variants are reported in Supplementary Fig. X because they represent model-internal signals or robustness checks rather than the core attribution comparison.

Supplementary caption draft:
Additional residue-level signals include attention-pooling weights, Gradient × Input, and SmoothGrad-IG. Similar near-random performance across multiple attribution families would indicate that poor epitope localization is not specific to a single attribution algorithm.
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/supplementary_all_signals_auroc.png
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/supplementary_all_signals_auroc.pdf
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/supplementary_all_signals_auprc.png
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/supplementary_all_signals_auprc.pdf
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/supplementary_all_signals_precision_at_k.png
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/supplementary_all_signals_precision_at_k.pdf

Main figure caption draft:
We compare a null random baseline, post-hoc protein-level explanations (Integrated Gradients and occlusion sensitivity), and a supervised MTL residue-level epitope head. Metrics are computed per protein against IEDB epitope annotations and averaged across proteins. Attention-pooling weights and additional gradient variants are reported in Supplementary Fig. X because they represent model-internal signals or robustness checks rather than the core attribution comparison.

Supplementary caption draft:
Additional residue-level signals include attention-pooling weights, Gradient × Input, and SmoothGrad-IG. Similar near-random performance across multiple attribution families would indicate that poor epitope localization is not specific to a single attribution algorithm.
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/label_scrambling_sanity_check_auroc.png
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/label_scrambling_sanity_check_auroc.pdf
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/label_scrambling_sanity_check_auprc.png
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/label_scrambling_sanity_check_auprc.pdf
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/label_scrambling_sanity_check_precision_at_k.png
Saved plot to: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/label_scrambling_sanity_check_precision_at_k.pdf
Label scrambling sanity check:
All methods should collapse to chance-level performance if the evaluation is well-calibrated.
If not, metric bias or leakage may be present.

{'main_dir': PosixPath('/Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main'),
 'supplementary_dir': PosixPath('/Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary'),
 'main_base': PosixPath('/Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main/main_localization.png'),
 'supplementary_base': PosixPath('/Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/supplementary_all_signals.png'),
 'scrambling_base': PosixPath('/Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/label_scrambling_sanity_check.png')}

In [10]:
print("Saved combined artifacts:")
for out_path in [MULTI_MODEL_ROWS_CSV, MULTI_MODEL_SUMMARY_CSV]:
    print(f"  {out_path}")
for label, out_path in figure_outputs.items():
    print(f"  {label}: {out_path}")

Saved combined artifacts:
  /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/probing/rows/all_models_probing_rows.csv
  /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/probing/summaries/all_models_probing_summary.csv
  main_dir: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main
  supplementary_dir: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary
  main_base: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/main/main_localization.png
  supplementary_base: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/supplementary_all_signals.png
  scrambling_base: /Users/jianzhouyao/Library/Mobile Documents/com~apple~CloudDocs/Universität/ETH/DL in Biology/XAllergen2.0/results/figures/supplementary/label_scrambling_sanity_check.png