## Google Colab Setup

This notebook can run either locally from the repo or on Google Colab.

Colab workflow:
- Mount Google Drive and save all trained-model outputs there immediately.
- Download only the exact code, data, RSA, and checkpoint files needed into `/content/XAllergen2.0`.
- Download a fresh ESM-2 snapshot from Hugging Face.
- Avoid `git clone`, which can be less reliable in hosted notebook runtimes.

Required GitHub-hosted artifacts:
- `models/baseline_frozen_esm2.pt`
- `data/rsa/deepalgpro_train_rsa.json.gz`
- `data/rsa/deepalgpro_test_rsa.json.gz`

In [1]:
import os
import shutil
import sys
import urllib.request
from pathlib import Path

IS_COLAB = 'google.colab' in sys.modules or Path('/content').exists()
os.environ['XALLERGEN_RUN_TARGET'] = 'colab' if IS_COLAB else 'local'

if IS_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    DRIVE_ROOT = Path('/content/drive/MyDrive/XAllergen2.0')
else:
    DRIVE_ROOT = None

if IS_COLAB:
    RUNTIME_ROOT = Path('/content/XAllergen2.0')
else:
    for _candidate in [Path.cwd(), *Path.cwd().parents]:
        if (_candidate / 'src' / 'xallergen').exists():
            RUNTIME_ROOT = _candidate
            break
    else:
        raise FileNotFoundError('Could not locate repo root with src/xallergen')

SRC_DIR = RUNTIME_ROOT / 'src'
PACKAGE_DIR = SRC_DIR / 'xallergen'
DATA_DIR = RUNTIME_ROOT / 'data'
RSA_DIR = DATA_DIR / 'rsa'
RUNTIME_MODELS_DIR = RUNTIME_ROOT / 'models'
RUNTIME_RESULTS_DIR = RUNTIME_ROOT / 'results'
HF_DIR = RUNTIME_ROOT / 'hf_models' / 'facebook_esm2_t6_8M_UR50D'

if IS_COLAB:
    MODELS_DIR = DRIVE_ROOT / 'models'
    RESULTS_DIR = DRIVE_ROOT / 'results'
else:
    MODELS_DIR = RUNTIME_MODELS_DIR
    RESULTS_DIR = RUNTIME_RESULTS_DIR

for path in [SRC_DIR, PACKAGE_DIR, DATA_DIR, RSA_DIR, RUNTIME_MODELS_DIR, RUNTIME_RESULTS_DIR, MODELS_DIR, RESULTS_DIR, HF_DIR]:
    path.mkdir(parents=True, exist_ok=True)

if IS_COLAB:
    from huggingface_hub import snapshot_download

    RAW = 'https://raw.githubusercontent.com/Jeffateth/XAllergen2.0/main'

    package_files = [
        '__init__.py',
        'baseline_notebook_utils.py',
        'baseline_sasa_experiment.py',
        'mtl_epitope_notebook_utils.py',
    ]
    data_files = [
        'deepalgpro_train_cleaned.csv',
        'deepalgpro_test_cleaned.csv',
        'positives_splitB.csv',
    ]
    rsa_files = [
        'deepalgpro_train_rsa.json.gz',
        'deepalgpro_test_rsa.json.gz',
    ]

    download_jobs = []
    download_jobs.extend((f'{RAW}/src/xallergen/{name}', PACKAGE_DIR / name) for name in package_files)
    download_jobs.extend((f'{RAW}/data/{name}', DATA_DIR / name) for name in data_files)
    download_jobs.extend((f'{RAW}/data/rsa/{name}', RSA_DIR / name) for name in rsa_files)
    download_jobs.append((f'{RAW}/models/baseline_frozen_esm2.pt', RUNTIME_MODELS_DIR / 'baseline_frozen_esm2.pt'))

    failed_urls = []
    for url, dst in download_jobs:
        try:
            urllib.request.urlretrieve(url, dst)
        except Exception as exc:
            failed_urls.append((url, str(exc)))

    if failed_urls:
        details = '\n'.join(f'  - {url} -> {err}' for url, err in failed_urls)
        raise RuntimeError('Failed to download required GitHub artifacts:\n' + details)

    fresh_model_path = snapshot_download(
        repo_id='facebook/esm2_t6_8M_UR50D',
        local_dir=HF_DIR,
        local_dir_use_symlinks=False,
        force_download=True,
        resume_download=False,
    )
    os.environ['XALLERGEN_HF_MODEL_DIR'] = str(fresh_model_path)

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

print(f'RUN_TARGET: {os.environ["XALLERGEN_RUN_TARGET"]}')
print(f'Runtime root: {RUNTIME_ROOT}')
print(f'Data dir: {DATA_DIR}')
print(f'RSA dir: {RSA_DIR}')
print(f'Runtime models dir: {RUNTIME_MODELS_DIR}')
print(f'Runtime results dir: {RUNTIME_RESULTS_DIR}')
print(f'Output models dir: {MODELS_DIR}')
print(f'Output results dir: {RESULTS_DIR}')
print(f'Source package dir: {PACKAGE_DIR}')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:189: UserWarning: The `resume_download` argument is deprecated and ignored in `snapshot_download`. Downloads always resume whenever possible.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `snapshot_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

RUN_TARGET: colab
Runtime root: /content/XAllergen2.0
Data dir: /content/XAllergen2.0/data
RSA dir: /content/XAllergen2.0/data/rsa
Models dir: /content/XAllergen2.0/models
Source package dir: /content/XAllergen2.0/src/xallergen

# Baseline ESM-2 with RSA Regularization

This notebook extends the frozen ESM-2 baseline with a single RSA regularization sweep driven by precomputed NetSurfP RSA values.

Design notes:
- The original `03_baseline_model_esm2.ipynb` remains the baseline reference.
- `lambda_rsa=0.0` is the classification-only baseline within the same sweep.
- The model stays unchanged: frozen ESM-2 backbone, attention pooling, and the existing classification head only.
- The RSA regularizer uses fixed precomputed RSA values from the split `.json.gz` artifacts and constrains attention pooling weights through the loss term.

In [2]:
import pandas as pd
import torch
from IPython.display import display
from sklearn.model_selection import train_test_split

from xallergen.baseline_notebook_utils import (
    RANDOM_STATE,
    build_tokenizer,
    load_baseline_checkpoint,
    seed_everything,
)
from xallergen.baseline_sasa_experiment import (
    RSARegularizationConfig,
    build_dataloader,
    compute_metrics,
    inspect_rsa_inputs,
    load_rsa_lookup_dicts,
    predict,
    run_lambda_rsa_sweep,
)

TRAIN_CSV = DATA_DIR / 'deepalgpro_train_cleaned.csv'
TEST_CSV = DATA_DIR / 'deepalgpro_test_cleaned.csv'
TRAIN_RSA_PATH = RSA_DIR / 'deepalgpro_train_rsa.json.gz'
TEST_RSA_PATH = RSA_DIR / 'deepalgpro_test_rsa.json.gz'
POSITIVES_SPLITB_CSV = DATA_DIR / 'positives_splitB.csv'
BASELINE_CHECKPOINT_PATH = RUNTIME_MODELS_DIR / 'baseline_frozen_esm2.pt'
RSA_RESULTS_DIR = RESULTS_DIR / 'rsa_regularization'
RSA_RESULTS_DIR.mkdir(parents=True, exist_ok=True)
SWEEP_SUMMARY_PATH = RSA_RESULTS_DIR / 'sweep_summary.csv'

for required_path in [
    TRAIN_CSV,
    TEST_CSV,
    TRAIN_RSA_PATH,
    TEST_RSA_PATH,
    POSITIVES_SPLITB_CSV,
    BASELINE_CHECKPOINT_PATH,
]:
    if not required_path.exists():
        raise FileNotFoundError(f'Missing required file: {required_path}')

CONFIG = RSARegularizationConfig(
    lambda_cls=1.0,
    lambda_rsa_values=(0.0, 0.1, 0.5, 1.0, 5.0),
    add_special_tokens=False,
)

seed_everything(RANDOM_STATE)
DEVICE = 'cuda' if torch.cuda.is_available() else ('mps' if torch.backends.mps.is_available() else 'cpu')
print(f'Device: {DEVICE}')
print(f'Tokenizer adds special tokens: {CONFIG.add_special_tokens}')
print(f'Baseline checkpoint: {BASELINE_CHECKPOINT_PATH}')
print(f'Sweep checkpoints + metrics dir: {RSA_RESULTS_DIR}')
if IS_COLAB:
    print(f'Google Drive root: {DRIVE_ROOT}')

Device: cuda
Tokenizer adds special tokens: False
Baseline checkpoint: /content/XAllergen2.0/models/baseline_frozen_esm2.pt
RSA results dir: /content/XAllergen2.0/results/rsa_regularization

In [3]:
train_df = pd.read_csv(TRAIN_CSV).copy()
test_df = pd.read_csv(TEST_CSV).copy()
for df in [train_df, test_df]:
    df['sequence_id'] = df['sequence_id'].astype(str).str.strip()
    df['sequence'] = df['sequence'].astype(str).str.strip().str.upper()
    df['label'] = df['label'].astype(int)

rsa_report_df = inspect_rsa_inputs(
    train_rsa_path=TRAIN_RSA_PATH,
    test_rsa_path=TEST_RSA_PATH,
    train_frame=train_df,
    test_frame=test_df,
)
display(rsa_report_df)

print(f'Train RSA file: {TRAIN_RSA_PATH}')
print(f'Test RSA file : {TEST_RSA_PATH}')

,path,format,compressed,n_sequences,rsa_min,rsa_max,rsa_in_unit_interval,min_length,max_length,expected_sequences,missing_sequences,extra_sequences,exact_id_match
0,/content/XAllergen2.0/data/rsa/deepalgpro_trai...,precomputed_rsa_json,True,5551,0.000877,0.978356,True,11,999,5551,0,0,True
1,/content/XAllergen2.0/data/rsa/deepalgpro_test...,precomputed_rsa_json,True,1377,0.000882,0.978507,True,11,979,1377,0,0,True

Train RSA file: /content/XAllergen2.0/data/rsa/deepalgpro_train_rsa.json.gz
Test RSA file : /content/XAllergen2.0/data/rsa/deepalgpro_test_rsa.json.gz

In [4]:
train_split_df, val_split_df = train_test_split(
    train_df,
    test_size=0.1,
    random_state=RANDOM_STATE,
    stratify=train_df['label'],
)
train_split_df = train_split_df.reset_index(drop=True).copy()
val_split_df = val_split_df.reset_index(drop=True).copy()

print(f'Train sequences: {len(train_split_df):,}')
print(f'Validation sequences: {len(val_split_df):,}')
print(f'Held-out test sequences: {len(test_df):,}')

Train sequences: 4,995
Validation sequences: 556
Held-out test sequences: 1,377

In [5]:
train_rsa_lookup, test_rsa_lookup, rsa_summary = load_rsa_lookup_dicts(
    train_rsa_path=TRAIN_RSA_PATH,
    test_rsa_path=TEST_RSA_PATH,
    train_frame=train_df,
    test_frame=test_df,
    add_special_tokens=CONFIG.add_special_tokens,
)
display(pd.DataFrame([rsa_summary['train'], rsa_summary['test']]))

,path,format,compressed,n_expected_sequences,n_parsed_sequences,n_missing_sequences,n_extra_sequences,n_length_mismatches,missing_sequence_ids,extra_sequence_ids,length_mismatches,add_special_tokens
0,/content/XAllergen2.0/data/rsa/deepalgpro_trai...,precomputed_rsa_json,True,5551,5551,0,0,0,[],[],[],False
1,/content/XAllergen2.0/data/rsa/deepalgpro_test...,precomputed_rsa_json,True,1377,1377,0,0,0,[],[],[],False

In [6]:
tokenizer = build_tokenizer()
val_loader_reference = build_dataloader(
    frame=val_split_df,
    rsa_lookup=train_rsa_lookup,
    tokenizer=tokenizer,
    batch_size=CONFIG.batch_size,
    shuffle=False,
    add_special_tokens=CONFIG.add_special_tokens,
)

baseline_model, _ = load_baseline_checkpoint(BASELINE_CHECKPOINT_PATH, DEVICE)
baseline_val_summary, baseline_val_predictions_df = predict(
    baseline_model,
    val_loader_reference,
    DEVICE,
    criterion=None,
    lambda_cls=CONFIG.lambda_cls,
    lambda_rsa=0.0,
    threshold=CONFIG.threshold,
)
baseline_val_metrics = compute_metrics(baseline_val_predictions_df, threshold=CONFIG.threshold)
print('Reference baseline checkpoint validation AUROC:', round(baseline_val_metrics['auroc'], 3))

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Reference baseline checkpoint validation AUROC: 0.978

In [7]:
rsa_summary_df = run_lambda_rsa_sweep(
    config=CONFIG,
    train_split_df=train_split_df,
    val_split_df=val_split_df,
    test_df=test_df,
    train_rsa_lookup=train_rsa_lookup,
    test_rsa_lookup=test_rsa_lookup,
    positives_splitb_csv=POSITIVES_SPLITB_CSV,
    output_dir=RSA_RESULTS_DIR,
    device=DEVICE,
)
sweep_summary_df = rsa_summary_df.loc[:, [
    'lambda_rsa',
    'epoch',
    'val_auroc',
    'val_precision',
    'val_recall',
    'val_f1',
    'val_mcc',
    'val_accuracy',
    'test_auroc',
    'test_precision',
    'test_recall',
    'test_f1',
    'test_mcc',
    'test_accuracy',
    'residue_auroc',
    'residue_auprc',
    'residue_precision_at_k',
]].copy()
SWEEP_SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
sweep_summary_df.to_csv(SWEEP_SUMMARY_PATH, index=False)
display(rsa_summary_df)
display(sweep_summary_df)

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=0:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43256 | train_rsa=None | train_total=0.43256 | val_cls=0.33752 | val_rsa=None | val_total=0.33752 | val_auroc=0.94359 | best=1
Epoch   2/30 | train_cls=0.31299 | train_rsa=None | train_total=0.31299 | val_cls=0.27909 | val_rsa=None | val_total=0.27909 | val_auroc=0.95712 | best=2
Epoch   3/30 | train_cls=0.27837 | train_rsa=None | train_total=0.27837 | val_cls=0.27041 | val_rsa=None | val_total=0.27041 | val_auroc=0.96114 | best=3
Epoch   4/30 | train_cls=0.25671 | train_rsa=None | train_total=0.25671 | val_cls=0.25006 | val_rsa=None | val_total=0.25006 | val_auroc=0.96522 | best=4
Epoch   5/30 | train_cls=0.23961 | train_rsa=None | train_total=0.23961 | val_cls=0.25322 | val_rsa=None | val_total=0.25322 | val_auroc=0.96283 | best=4
Epoch   6/30 | train_cls=0.22956 | train_rsa=None | train_total=0.22956 | val_cls=0.23530 | val_rsa=None | val_total=0.23530 | val_auroc=0.96843 | best=6
Epoch   7/30 | train_cls=0.21919 | train_rsa=None | train_total=0.21919 | val_cls=0.22239 | val_rsa=None | val_total=0.22239 | val_auroc=0.97274 | best=7
Epoch   8/30 | train_cls=0.20615 | train_rsa=None | train_total=0.20615 | val_cls=0.23249 | val_rsa=None | val_total=0.23249 | val_auroc=0.97186 | best=7
Epoch   9/30 | train_cls=0.19490 | train_rsa=None | train_total=0.19490 | val_cls=0.20686 | val_rsa=None | val_total=0.20686 | val_auroc=0.97547 | best=9
Epoch  10/30 | train_cls=0.18530 | train_rsa=None | train_total=0.18530 | val_cls=0.20967 | val_rsa=None | val_total=0.20967 | val_auroc=0.97438 | best=9
Epoch  11/30 | train_cls=0.18160 | train_rsa=None | train_total=0.18160 | val_cls=0.19878 | val_rsa=None | val_total=0.19878 | val_auroc=0.97704 | best=11
Epoch  12/30 | train_cls=0.17369 | train_rsa=None | train_total=0.17369 | val_cls=0.21557 | val_rsa=None | val_total=0.21557 | val_auroc=0.97653 | best=11
Epoch  13/30 | train_cls=0.17102 | train_rsa=None | train_total=0.17102 | val_cls=0.20262 | val_rsa=None | val_total=0.20262 | val_auroc=0.97686 | best=11
Epoch  14/30 | train_cls=0.15796 | train_rsa=None | train_total=0.15796 | val_cls=0.19979 | val_rsa=None | val_total=0.19979 | val_auroc=0.97664 | best=11
Epoch  15/30 | train_cls=0.16116 | train_rsa=None | train_total=0.16116 | val_cls=0.20061 | val_rsa=None | val_total=0.20061 | val_auroc=0.97763 | best=11
Epoch  16/30 | train_cls=0.15034 | train_rsa=None | train_total=0.15034 | val_cls=0.19262 | val_rsa=None | val_total=0.19262 | val_auroc=0.97798 | best=16
Epoch  17/30 | train_cls=0.14713 | train_rsa=None | train_total=0.14713 | val_cls=0.20263 | val_rsa=None | val_total=0.20263 | val_auroc=0.97757 | best=16
Epoch  18/30 | train_cls=0.14533 | train_rsa=None | train_total=0.14533 | val_cls=0.20372 | val_rsa=None | val_total=0.20372 | val_auroc=0.97618 | best=16
Epoch  19/30 | train_cls=0.14157 | train_rsa=None | train_total=0.14157 | val_cls=0.19824 | val_rsa=None | val_total=0.19824 | val_auroc=0.97828 | best=16
Epoch  20/30 | train_cls=0.13148 | train_rsa=None | train_total=0.13148 | val_cls=0.20307 | val_rsa=None | val_total=0.20307 | val_auroc=0.97624 | best=16
Epoch  21/30 | train_cls=0.12715 | train_rsa=None | train_total=0.12715 | val_cls=0.19397 | val_rsa=None | val_total=0.19397 | val_auroc=0.97882 | best=16
Early stopping triggered at epoch 21.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=0.1:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43254 | train_rsa=0.00328 | train_total=0.43287 | val_cls=0.33728 | val_rsa=0.00305 | val_total=0.33758 | val_auroc=0.94346 | best=1
Epoch   2/30 | train_cls=0.31279 | train_rsa=0.00314 | train_total=0.31311 | val_cls=0.27889 | val_rsa=0.00299 | val_total=0.27919 | val_auroc=0.95717 | best=2
Epoch   3/30 | train_cls=0.27852 | train_rsa=0.00310 | train_total=0.27883 | val_cls=0.26994 | val_rsa=0.00295 | val_total=0.27024 | val_auroc=0.96132 | best=3
Epoch   4/30 | train_cls=0.25709 | train_rsa=0.00308 | train_total=0.25740 | val_cls=0.24960 | val_rsa=0.00294 | val_total=0.24989 | val_auroc=0.96545 | best=4
Epoch   5/30 | train_cls=0.23965 | train_rsa=0.00306 | train_total=0.23996 | val_cls=0.25165 | val_rsa=0.00294 | val_total=0.25194 | val_auroc=0.96329 | best=4
Epoch   6/30 | train_cls=0.22969 | train_rsa=0.00305 | train_total=0.23000 | val_cls=0.23624 | val_rsa=0.00292 | val_total=0.23653 | val_auroc=0.96825 | best=6
Epoch   7/30 | train_cls=0.21996 | train_rsa=0.00305 | train_total=0.22027 | val_cls=0.22404 | val_rsa=0.00287 | val_total=0.22432 | val_auroc=0.97268 | best=7
Epoch   8/30 | train_cls=0.20493 | train_rsa=0.00304 | train_total=0.20523 | val_cls=0.23232 | val_rsa=0.00293 | val_total=0.23262 | val_auroc=0.97150 | best=7
Epoch   9/30 | train_cls=0.19389 | train_rsa=0.00304 | train_total=0.19420 | val_cls=0.20847 | val_rsa=0.00288 | val_total=0.20876 | val_auroc=0.97510 | best=9
Epoch  10/30 | train_cls=0.18447 | train_rsa=0.00304 | train_total=0.18477 | val_cls=0.20870 | val_rsa=0.00290 | val_total=0.20899 | val_auroc=0.97460 | best=9
Epoch  11/30 | train_cls=0.18029 | train_rsa=0.00303 | train_total=0.18059 | val_cls=0.19990 | val_rsa=0.00291 | val_total=0.20019 | val_auroc=0.97681 | best=11
Epoch  12/30 | train_cls=0.17280 | train_rsa=0.00304 | train_total=0.17310 | val_cls=0.21691 | val_rsa=0.00293 | val_total=0.21720 | val_auroc=0.97647 | best=11
Epoch  13/30 | train_cls=0.17075 | train_rsa=0.00303 | train_total=0.17105 | val_cls=0.20186 | val_rsa=0.00291 | val_total=0.20215 | val_auroc=0.97670 | best=11
Epoch  14/30 | train_cls=0.15770 | train_rsa=0.00302 | train_total=0.15801 | val_cls=0.20123 | val_rsa=0.00292 | val_total=0.20152 | val_auroc=0.97634 | best=11
Epoch  15/30 | train_cls=0.16010 | train_rsa=0.00303 | train_total=0.16040 | val_cls=0.19984 | val_rsa=0.00290 | val_total=0.20013 | val_auroc=0.97772 | best=11
Epoch  16/30 | train_cls=0.14980 | train_rsa=0.00302 | train_total=0.15010 | val_cls=0.19248 | val_rsa=0.00288 | val_total=0.19277 | val_auroc=0.97781 | best=16
Epoch  17/30 | train_cls=0.14754 | train_rsa=0.00302 | train_total=0.14784 | val_cls=0.19978 | val_rsa=0.00292 | val_total=0.20007 | val_auroc=0.97829 | best=16
Epoch  18/30 | train_cls=0.14399 | train_rsa=0.00303 | train_total=0.14429 | val_cls=0.20402 | val_rsa=0.00291 | val_total=0.20431 | val_auroc=0.97625 | best=16
Epoch  19/30 | train_cls=0.13951 | train_rsa=0.00303 | train_total=0.13982 | val_cls=0.19404 | val_rsa=0.00288 | val_total=0.19433 | val_auroc=0.97889 | best=16
Epoch  20/30 | train_cls=0.13004 | train_rsa=0.00301 | train_total=0.13034 | val_cls=0.20147 | val_rsa=0.00291 | val_total=0.20176 | val_auroc=0.97679 | best=16
Epoch  21/30 | train_cls=0.12615 | train_rsa=0.00302 | train_total=0.12645 | val_cls=0.19476 | val_rsa=0.00292 | val_total=0.19506 | val_auroc=0.97854 | best=16
Early stopping triggered at epoch 21.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=0.5:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43233 | train_rsa=0.00327 | train_total=0.43396 | val_cls=0.33700 | val_rsa=0.00303 | val_total=0.33851 | val_auroc=0.94375 | best=1
Epoch   2/30 | train_cls=0.31270 | train_rsa=0.00312 | train_total=0.31426 | val_cls=0.27856 | val_rsa=0.00297 | val_total=0.28005 | val_auroc=0.95717 | best=2
Epoch   3/30 | train_cls=0.27854 | train_rsa=0.00308 | train_total=0.28008 | val_cls=0.27014 | val_rsa=0.00293 | val_total=0.27160 | val_auroc=0.96103 | best=3
Epoch   4/30 | train_cls=0.25678 | train_rsa=0.00306 | train_total=0.25832 | val_cls=0.24976 | val_rsa=0.00292 | val_total=0.25122 | val_auroc=0.96545 | best=4
Epoch   5/30 | train_cls=0.23959 | train_rsa=0.00305 | train_total=0.24111 | val_cls=0.25319 | val_rsa=0.00292 | val_total=0.25465 | val_auroc=0.96307 | best=4
Epoch   6/30 | train_cls=0.22983 | train_rsa=0.00303 | train_total=0.23134 | val_cls=0.23603 | val_rsa=0.00289 | val_total=0.23747 | val_auroc=0.96846 | best=6
Epoch   7/30 | train_cls=0.21964 | train_rsa=0.00303 | train_total=0.22115 | val_cls=0.22294 | val_rsa=0.00285 | val_total=0.22436 | val_auroc=0.97260 | best=7
Epoch   8/30 | train_cls=0.20570 | train_rsa=0.00301 | train_total=0.20721 | val_cls=0.23315 | val_rsa=0.00291 | val_total=0.23460 | val_auroc=0.97136 | best=7
Epoch   9/30 | train_cls=0.19508 | train_rsa=0.00301 | train_total=0.19659 | val_cls=0.20823 | val_rsa=0.00285 | val_total=0.20966 | val_auroc=0.97488 | best=9
Epoch  10/30 | train_cls=0.18623 | train_rsa=0.00302 | train_total=0.18774 | val_cls=0.21059 | val_rsa=0.00288 | val_total=0.21203 | val_auroc=0.97442 | best=9
Epoch  11/30 | train_cls=0.18123 | train_rsa=0.00301 | train_total=0.18274 | val_cls=0.20102 | val_rsa=0.00288 | val_total=0.20246 | val_auroc=0.97607 | best=11
Epoch  12/30 | train_cls=0.17322 | train_rsa=0.00301 | train_total=0.17472 | val_cls=0.21683 | val_rsa=0.00290 | val_total=0.21828 | val_auroc=0.97625 | best=11
Epoch  13/30 | train_cls=0.17180 | train_rsa=0.00300 | train_total=0.17330 | val_cls=0.20695 | val_rsa=0.00290 | val_total=0.20840 | val_auroc=0.97581 | best=11
Epoch  14/30 | train_cls=0.15891 | train_rsa=0.00299 | train_total=0.16040 | val_cls=0.20155 | val_rsa=0.00289 | val_total=0.20300 | val_auroc=0.97593 | best=11
Epoch  15/30 | train_cls=0.16014 | train_rsa=0.00300 | train_total=0.16164 | val_cls=0.20264 | val_rsa=0.00287 | val_total=0.20408 | val_auroc=0.97699 | best=11
Epoch  16/30 | train_cls=0.15084 | train_rsa=0.00299 | train_total=0.15234 | val_cls=0.19677 | val_rsa=0.00286 | val_total=0.19820 | val_auroc=0.97688 | best=16
Epoch  17/30 | train_cls=0.14867 | train_rsa=0.00299 | train_total=0.15016 | val_cls=0.20144 | val_rsa=0.00290 | val_total=0.20289 | val_auroc=0.97759 | best=16
Epoch  18/30 | train_cls=0.14450 | train_rsa=0.00300 | train_total=0.14600 | val_cls=0.20555 | val_rsa=0.00289 | val_total=0.20700 | val_auroc=0.97576 | best=16
Epoch  19/30 | train_cls=0.14178 | train_rsa=0.00300 | train_total=0.14328 | val_cls=0.20447 | val_rsa=0.00286 | val_total=0.20590 | val_auroc=0.97766 | best=16
Epoch  20/30 | train_cls=0.13200 | train_rsa=0.00298 | train_total=0.13349 | val_cls=0.20020 | val_rsa=0.00288 | val_total=0.20163 | val_auroc=0.97687 | best=16
Epoch  21/30 | train_cls=0.12833 | train_rsa=0.00299 | train_total=0.12983 | val_cls=0.19304 | val_rsa=0.00289 | val_total=0.19448 | val_auroc=0.97862 | best=21
Epoch  22/30 | train_cls=0.12794 | train_rsa=0.00299 | train_total=0.12943 | val_cls=0.21272 | val_rsa=0.00289 | val_total=0.21416 | val_auroc=0.97468 | best=21
Epoch  23/30 | train_cls=0.12427 | train_rsa=0.00299 | train_total=0.12576 | val_cls=0.21242 | val_rsa=0.00290 | val_total=0.21387 | val_auroc=0.97602 | best=21
Epoch  24/30 | train_cls=0.11878 | train_rsa=0.00299 | train_total=0.12027 | val_cls=0.19759 | val_rsa=0.00286 | val_total=0.19902 | val_auroc=0.97726 | best=21
Epoch  25/30 | train_cls=0.11796 | train_rsa=0.00298 | train_total=0.11945 | val_cls=0.20413 | val_rsa=0.00289 | val_total=0.20558 | val_auroc=0.97779 | best=21
Epoch  26/30 | train_cls=0.10946 | train_rsa=0.00299 | train_total=0.11096 | val_cls=0.21073 | val_rsa=0.00287 | val_total=0.21217 | val_auroc=0.97828 | best=21
Early stopping triggered at epoch 26.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=1:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43203 | train_rsa=0.00325 | train_total=0.43528 | val_cls=0.33681 | val_rsa=0.00302 | val_total=0.33983 | val_auroc=0.94364 | best=1
Epoch   2/30 | train_cls=0.31299 | train_rsa=0.00310 | train_total=0.31610 | val_cls=0.27879 | val_rsa=0.00296 | val_total=0.28174 | val_auroc=0.95720 | best=2
Epoch   3/30 | train_cls=0.27861 | train_rsa=0.00306 | train_total=0.28167 | val_cls=0.26966 | val_rsa=0.00291 | val_total=0.27257 | val_auroc=0.96117 | best=3
Epoch   4/30 | train_cls=0.25668 | train_rsa=0.00304 | train_total=0.25973 | val_cls=0.24908 | val_rsa=0.00290 | val_total=0.25199 | val_auroc=0.96547 | best=4
Epoch   5/30 | train_cls=0.23888 | train_rsa=0.00303 | train_total=0.24191 | val_cls=0.25143 | val_rsa=0.00290 | val_total=0.25433 | val_auroc=0.96338 | best=4
Epoch   6/30 | train_cls=0.22888 | train_rsa=0.00302 | train_total=0.23190 | val_cls=0.23523 | val_rsa=0.00288 | val_total=0.23810 | val_auroc=0.96853 | best=6
Epoch   7/30 | train_cls=0.21853 | train_rsa=0.00301 | train_total=0.22154 | val_cls=0.22266 | val_rsa=0.00283 | val_total=0.22549 | val_auroc=0.97255 | best=7
Epoch   8/30 | train_cls=0.20452 | train_rsa=0.00299 | train_total=0.20751 | val_cls=0.23140 | val_rsa=0.00289 | val_total=0.23429 | val_auroc=0.97154 | best=7
Epoch   9/30 | train_cls=0.19367 | train_rsa=0.00299 | train_total=0.19666 | val_cls=0.20754 | val_rsa=0.00284 | val_total=0.21038 | val_auroc=0.97519 | best=9
Epoch  10/30 | train_cls=0.18472 | train_rsa=0.00299 | train_total=0.18772 | val_cls=0.20847 | val_rsa=0.00286 | val_total=0.21133 | val_auroc=0.97457 | best=9
Epoch  11/30 | train_cls=0.18073 | train_rsa=0.00299 | train_total=0.18373 | val_cls=0.19913 | val_rsa=0.00286 | val_total=0.20200 | val_auroc=0.97651 | best=11
Epoch  12/30 | train_cls=0.17201 | train_rsa=0.00299 | train_total=0.17500 | val_cls=0.21572 | val_rsa=0.00288 | val_total=0.21860 | val_auroc=0.97638 | best=11
Epoch  13/30 | train_cls=0.17029 | train_rsa=0.00298 | train_total=0.17328 | val_cls=0.20327 | val_rsa=0.00287 | val_total=0.20614 | val_auroc=0.97633 | best=11
Epoch  14/30 | train_cls=0.15780 | train_rsa=0.00297 | train_total=0.16077 | val_cls=0.20043 | val_rsa=0.00287 | val_total=0.20330 | val_auroc=0.97644 | best=11
Epoch  15/30 | train_cls=0.15981 | train_rsa=0.00298 | train_total=0.16279 | val_cls=0.20302 | val_rsa=0.00285 | val_total=0.20587 | val_auroc=0.97673 | best=11
Epoch  16/30 | train_cls=0.15050 | train_rsa=0.00297 | train_total=0.15347 | val_cls=0.19590 | val_rsa=0.00283 | val_total=0.19873 | val_auroc=0.97701 | best=16
Epoch  17/30 | train_cls=0.14826 | train_rsa=0.00296 | train_total=0.15123 | val_cls=0.20485 | val_rsa=0.00287 | val_total=0.20773 | val_auroc=0.97674 | best=16
Epoch  18/30 | train_cls=0.14452 | train_rsa=0.00297 | train_total=0.14749 | val_cls=0.20973 | val_rsa=0.00286 | val_total=0.21259 | val_auroc=0.97494 | best=16
Epoch  19/30 | train_cls=0.14091 | train_rsa=0.00297 | train_total=0.14388 | val_cls=0.21100 | val_rsa=0.00284 | val_total=0.21384 | val_auroc=0.97670 | best=16
Epoch  20/30 | train_cls=0.13322 | train_rsa=0.00296 | train_total=0.13618 | val_cls=0.20083 | val_rsa=0.00286 | val_total=0.20369 | val_auroc=0.97664 | best=16
Epoch  21/30 | train_cls=0.12745 | train_rsa=0.00297 | train_total=0.13041 | val_cls=0.19657 | val_rsa=0.00285 | val_total=0.19942 | val_auroc=0.97803 | best=16
Early stopping triggered at epoch 21.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=5:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43114 | train_rsa=0.00314 | train_total=0.44686 | val_cls=0.33539 | val_rsa=0.00290 | val_total=0.34989 | val_auroc=0.94433 | best=1
Epoch   2/30 | train_cls=0.31391 | train_rsa=0.00297 | train_total=0.32878 | val_cls=0.27803 | val_rsa=0.00284 | val_total=0.29224 | val_auroc=0.95711 | best=2
Epoch   3/30 | train_cls=0.28041 | train_rsa=0.00293 | train_total=0.29506 | val_cls=0.27208 | val_rsa=0.00279 | val_total=0.28603 | val_auroc=0.96021 | best=3
Epoch   4/30 | train_cls=0.25949 | train_rsa=0.00291 | train_total=0.27403 | val_cls=0.25050 | val_rsa=0.00276 | val_total=0.26431 | val_auroc=0.96488 | best=4
Epoch   5/30 | train_cls=0.24275 | train_rsa=0.00288 | train_total=0.25716 | val_cls=0.25507 | val_rsa=0.00277 | val_total=0.26893 | val_auroc=0.96245 | best=4
Epoch   6/30 | train_cls=0.23268 | train_rsa=0.00287 | train_total=0.24705 | val_cls=0.23794 | val_rsa=0.00273 | val_total=0.25161 | val_auroc=0.96767 | best=6
Epoch   7/30 | train_cls=0.22436 | train_rsa=0.00286 | train_total=0.23867 | val_cls=0.22660 | val_rsa=0.00268 | val_total=0.23999 | val_auroc=0.97167 | best=7
Epoch   8/30 | train_cls=0.20931 | train_rsa=0.00284 | train_total=0.22352 | val_cls=0.23553 | val_rsa=0.00275 | val_total=0.24927 | val_auroc=0.97077 | best=7
Epoch   9/30 | train_cls=0.19784 | train_rsa=0.00284 | train_total=0.21205 | val_cls=0.21115 | val_rsa=0.00269 | val_total=0.22461 | val_auroc=0.97419 | best=9
Epoch  10/30 | train_cls=0.19008 | train_rsa=0.00285 | train_total=0.20431 | val_cls=0.21374 | val_rsa=0.00270 | val_total=0.22726 | val_auroc=0.97340 | best=9
Epoch  11/30 | train_cls=0.18601 | train_rsa=0.00283 | train_total=0.20017 | val_cls=0.20396 | val_rsa=0.00271 | val_total=0.21750 | val_auroc=0.97561 | best=11
Epoch  12/30 | train_cls=0.17731 | train_rsa=0.00283 | train_total=0.19144 | val_cls=0.21433 | val_rsa=0.00273 | val_total=0.22797 | val_auroc=0.97574 | best=11
Epoch  13/30 | train_cls=0.17254 | train_rsa=0.00282 | train_total=0.18662 | val_cls=0.20831 | val_rsa=0.00271 | val_total=0.22188 | val_auroc=0.97506 | best=11
Epoch  14/30 | train_cls=0.16309 | train_rsa=0.00280 | train_total=0.17708 | val_cls=0.20690 | val_rsa=0.00270 | val_total=0.22038 | val_auroc=0.97471 | best=11
Epoch  15/30 | train_cls=0.16163 | train_rsa=0.00280 | train_total=0.17561 | val_cls=0.20632 | val_rsa=0.00268 | val_total=0.21971 | val_auroc=0.97622 | best=11
Epoch  16/30 | train_cls=0.15451 | train_rsa=0.00279 | train_total=0.16846 | val_cls=0.20249 | val_rsa=0.00266 | val_total=0.21580 | val_auroc=0.97554 | best=16
Epoch  17/30 | train_cls=0.14908 | train_rsa=0.00278 | train_total=0.16296 | val_cls=0.20860 | val_rsa=0.00270 | val_total=0.22210 | val_auroc=0.97604 | best=16
Epoch  18/30 | train_cls=0.14733 | train_rsa=0.00279 | train_total=0.16127 | val_cls=0.21308 | val_rsa=0.00269 | val_total=0.22652 | val_auroc=0.97438 | best=16
Epoch  19/30 | train_cls=0.14314 | train_rsa=0.00278 | train_total=0.15704 | val_cls=0.21039 | val_rsa=0.00267 | val_total=0.22373 | val_auroc=0.97605 | best=16
Epoch  20/30 | train_cls=0.13613 | train_rsa=0.00276 | train_total=0.14995 | val_cls=0.20704 | val_rsa=0.00267 | val_total=0.22042 | val_auroc=0.97530 | best=16
Epoch  21/30 | train_cls=0.13051 | train_rsa=0.00277 | train_total=0.14436 | val_cls=0.20047 | val_rsa=0.00267 | val_total=0.21381 | val_auroc=0.97752 | best=21
Epoch  22/30 | train_cls=0.13018 | train_rsa=0.00277 | train_total=0.14401 | val_cls=0.22222 | val_rsa=0.00267 | val_total=0.23556 | val_auroc=0.97376 | best=21
Epoch  23/30 | train_cls=0.12460 | train_rsa=0.00277 | train_total=0.13842 | val_cls=0.21286 | val_rsa=0.00266 | val_total=0.22618 | val_auroc=0.97530 | best=21
Epoch  24/30 | train_cls=0.12030 | train_rsa=0.00276 | train_total=0.13410 | val_cls=0.20097 | val_rsa=0.00264 | val_total=0.21418 | val_auroc=0.97691 | best=21
Epoch  25/30 | train_cls=0.11570 | train_rsa=0.00275 | train_total=0.12946 | val_cls=0.20741 | val_rsa=0.00267 | val_total=0.22075 | val_auroc=0.97714 | best=21
Epoch  26/30 | train_cls=0.11145 | train_rsa=0.00276 | train_total=0.12525 | val_cls=0.21012 | val_rsa=0.00265 | val_total=0.22336 | val_auroc=0.97739 | best=21
Early stopping triggered at epoch 26.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

,lambda_rsa,epoch,val_auroc,val_f1,test_auroc,test_f1,test_mcc,residue_auroc,residue_auprc,residue_precision_at_k,checkpoint_path,metrics_path,probe_rows_path
0,0.0,16,0.977983,0.921676,0.969860,0.915997,0.833569,0.4677,0.2529,0.2163,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...
1,0.1,16,0.977815,0.923358,0.969347,0.913869,0.829261,0.4679,0.2527,0.2165,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...
2,0.5,21,0.978617,0.928177,0.969732,0.921817,0.847402,0.4660,0.2519,0.2148,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...
3,1.0,16,0.977012,0.925046,0.970542,0.918442,0.839039,0.4667,0.2517,0.2188,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...
4,5.0,21,0.977517,0.928177,0.969447,0.921248,0.845968,0.4570,0.2474,0.2146,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...,/content/XAllergen2.0/results/rsa_regularizati...

   lambda_rsa  val_auroc    val_f1  epoch
0         0.0   0.977983  0.921676     16
1         0.1   0.977815  0.923358     16
2         0.5   0.978617  0.928177     21
3         1.0   0.977012  0.925046     16
4         5.0   0.977517  0.928177     21

In [ ]:
lambda_zero_row = sweep_summary_df.loc[sweep_summary_df['lambda_rsa'].eq(0.0)].copy()
if not lambda_zero_row.empty:
    sweep_val_auroc = float(lambda_zero_row.iloc[0]['val_auroc'])
    print('Reference baseline checkpoint val AUROC:', round(baseline_val_metrics['auroc'], 3))
    print('lambda_rsa=0 sweep val AUROC        :', round(sweep_val_auroc, 3))
    print('Match to three decimals             :', round(baseline_val_metrics['auroc'], 3) == round(sweep_val_auroc, 3))
print(f'Saved sweep summary to: {SWEEP_SUMMARY_PATH}')
print(f'Sweep directory: {RSA_RESULTS_DIR}')
print('Best checkpoints are saved during training as each lambda improves validation loss.')
if IS_COLAB:
    print(f'All outputs were written directly to Google Drive under: {DRIVE_ROOT}')

Reference baseline checkpoint val AUROC: 0.978
lambda_rsa=0 sweep val AUROC        : 0.978
Match to three decimals             : True
Saved sweep summary to: /content/XAllergen2.0/results/rsa_regularization/sweep_summary.csv

:

In [ ]:
# Shut down the runtime after everything above has finished.
import os
os.kill(os.getpid(), 9)

:

: