## Google Colab Setup

This notebook can run either locally from the repo or on Google Colab.

Colab workflow:
- Mount Google Drive and save all trained-model outputs there immediately.
- Download only the exact code, data, and pre-computed structural-feature files needed into `/content/XAllergen2.0`.
- Download a fresh ESM-2 snapshot from Hugging Face.
- Avoid `git clone`, which can be less reliable in hosted notebook runtimes.

Required GitHub-hosted artifacts:
- `models/baseline_frozen_esm2.pt`
- `data/ss3/deepalgpro_train_ss3_structured.json.gz` / `deepalgpro_test_ss3_structured.json.gz`
- `data/disorder/deepalgpro_train_disorder.json.gz` / `deepalgpro_test_disorder.json.gz`

Section C reads `results/rsa_regularization/sweep_summary.csv` produced by notebook 12.
On Colab this is read from Google Drive; run notebook 12 first and keep Drive mounted.

In [3]:
import os
import sys
import urllib.request
from pathlib import Path

IS_COLAB = 'google.colab' in sys.modules or Path('/content').exists()
os.environ['XALLERGEN_RUN_TARGET'] = 'colab' if IS_COLAB else 'local'

if IS_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    DRIVE_ROOT = Path('/content/drive/MyDrive/XAllergen2.0')
else:
    DRIVE_ROOT = None

if IS_COLAB:
    RUNTIME_ROOT = Path('/content/XAllergen2.0')
else:
    for _candidate in [Path.cwd(), *Path.cwd().parents]:
        if (_candidate / 'src' / 'xallergen').exists():
            RUNTIME_ROOT = _candidate
            break
    else:
        raise FileNotFoundError('Could not locate repo root with src/xallergen')

SRC_DIR = RUNTIME_ROOT / 'src'
PACKAGE_DIR = SRC_DIR / 'xallergen'
DATA_DIR = RUNTIME_ROOT / 'data'
SS3_DIR = DATA_DIR / 'ss3'
DISORDER_DIR = DATA_DIR / 'disorder'
RUNTIME_MODELS_DIR = RUNTIME_ROOT / 'models'
RUNTIME_RESULTS_DIR = RUNTIME_ROOT / 'results'
HF_DIR = RUNTIME_ROOT / 'hf_models' / 'facebook_esm2_t6_8M_UR50D'

if IS_COLAB:
    MODELS_DIR = DRIVE_ROOT / 'models'
    RESULTS_DIR = DRIVE_ROOT / 'results'
else:
    MODELS_DIR = RUNTIME_MODELS_DIR
    RESULTS_DIR = RUNTIME_RESULTS_DIR

for path in [
    SRC_DIR, PACKAGE_DIR, DATA_DIR, SS3_DIR, DISORDER_DIR,
    RUNTIME_MODELS_DIR, RUNTIME_RESULTS_DIR, MODELS_DIR, RESULTS_DIR, HF_DIR,
]:
    path.mkdir(parents=True, exist_ok=True)

if IS_COLAB:
    from huggingface_hub import snapshot_download

    RAW = 'https://raw.githubusercontent.com/Jeffateth/XAllergen2.0/main'

    package_files = [
        '__init__.py',
        'baseline_notebook_utils.py',
        'baseline_sasa_experiment.py',
        'mtl_epitope_notebook_utils.py',
        'rsa_preprocessing.py',
    ]
    data_files = [
        'deepalgpro_train_cleaned.csv',
        'deepalgpro_test_cleaned.csv',
        'positives_splitB.csv',
    ]
    ss3_files = [
        'deepalgpro_train_ss3_structured.json.gz',
        'deepalgpro_test_ss3_structured.json.gz',
    ]
    disorder_files = [
        'deepalgpro_train_disorder.json.gz',
        'deepalgpro_test_disorder.json.gz',
    ]

    download_jobs = []
    download_jobs.extend((f'{RAW}/src/xallergen/{name}', PACKAGE_DIR / name) for name in package_files)
    download_jobs.extend((f'{RAW}/data/{name}', DATA_DIR / name) for name in data_files)
    download_jobs.extend((f'{RAW}/data/ss3/{name}', SS3_DIR / name) for name in ss3_files)
    download_jobs.extend((f'{RAW}/data/disorder/{name}', DISORDER_DIR / name) for name in disorder_files)
    download_jobs.append((f'{RAW}/models/baseline_frozen_esm2.pt', RUNTIME_MODELS_DIR / 'baseline_frozen_esm2.pt'))

    failed_urls = []
    for url, dst in download_jobs:
        try:
            urllib.request.urlretrieve(url, dst)
        except Exception as exc:
            failed_urls.append((url, str(exc)))

    if failed_urls:
        details = '\n'.join(f'  - {url} -> {err}' for url, err in failed_urls)
        raise RuntimeError('Failed to download required GitHub artifacts:\n' + details)

    fresh_model_path = snapshot_download(
        repo_id='facebook/esm2_t6_8M_UR50D',
        local_dir=HF_DIR,
        local_dir_use_symlinks=False,
        force_download=True,
        resume_download=False,
    )
    os.environ['XALLERGEN_HF_MODEL_DIR'] = str(fresh_model_path)

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

print(f'RUN_TARGET: {os.environ["XALLERGEN_RUN_TARGET"]}')
print(f'Runtime root: {RUNTIME_ROOT}')
print(f'SS3 dir: {SS3_DIR}')
print(f'Disorder dir: {DISORDER_DIR}')
print(f'Output results dir: {RESULTS_DIR}')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:189: UserWarning: The `resume_download` argument is deprecated and ignored in `snapshot_download`. Downloads always resume whenever possible.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `snapshot_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

RUN_TARGET: colab
Runtime root: /content/XAllergen2.0
SS3 dir: /content/XAllergen2.0/data/ss3
Disorder dir: /content/XAllergen2.0/data/disorder
Output results dir: /content/drive/MyDrive/XAllergen2.0/results

# Section A — SS3-Structured Regularization Sweep

Tests whether penalising attention on coil/loop residues improves allergenicity classification
and residue-level localisation. The regularization loss is:

$$\mathcal{L} = \lambda_\text{cls}\mathcal{L}_\text{cls} + \lambda_\text{reg} \cdot \frac{1}{L}\sum_i \alpha_i (1 - f_i)$$

where $f_i = 1.0$ for helix (H) or strand (E) residues and $f_i = 0.0$ for coil/loop (C).
The $(1 - f_i)$ term is therefore 0 for structured residues and 1 for coil residues,
so the loss penalises attention weight on unstructured positions.

No new model heads or trainable components are introduced; the frozen ESM-2 backbone is unchanged.
Section C compares the best SS3-structured λ against the RSA baseline from notebook 12.

In [4]:
import importlib
import sys
from pathlib import Path


def _find_repo_root(start: Path) -> Path:
    for candidate in [start.resolve(), *start.resolve().parents]:
        if (candidate / 'pyproject.toml').exists() or (candidate / 'src' / 'xallergen').exists():
            return candidate
    raise FileNotFoundError('Could not find repo root containing pyproject.toml or src/xallergen')


if 'DATA_DIR' not in globals():
    RUNTIME_ROOT = _find_repo_root(Path.cwd())
    SRC_DIR = RUNTIME_ROOT / 'src'
    DATA_DIR = RUNTIME_ROOT / 'data'
    SS3_DIR = DATA_DIR / 'ss3'
    DISORDER_DIR = DATA_DIR / 'disorder'
    RUNTIME_MODELS_DIR = RUNTIME_ROOT / 'models'
    RESULTS_DIR = RUNTIME_ROOT / 'results'
    if str(SRC_DIR) not in sys.path:
        sys.path.insert(0, str(SRC_DIR))

missing_modules = []
for module_name in ('numpy', 'pandas', 'torch', 'IPython', 'sklearn'):
    try:
        importlib.import_module(module_name)
    except ModuleNotFoundError:
        missing_modules.append(module_name)

if missing_modules:
    missing = ', '.join(missing_modules)
    raise ModuleNotFoundError(
        'Notebook dependencies are missing from the active kernel: '
        f'{missing}. Run `make setup` and select `.venv/bin/python` or the '
        '`Python (xallergen2)` kernel before rerunning this cell.'
    )

import pandas as pd
import torch
from IPython.display import display
from sklearn.model_selection import train_test_split

from xallergen.baseline_notebook_utils import (
    RANDOM_STATE,
    seed_everything,
)
from xallergen.baseline_sasa_experiment import (
    RSARegularizationConfig,
    inspect_rsa_inputs,
    load_rsa_lookup_dicts,
    run_lambda_rsa_sweep,
)
from xallergen.rsa_preprocessing import compute_rsa_ss3_structured_correlation

TRAIN_CSV = DATA_DIR / 'deepalgpro_train_cleaned.csv'
TEST_CSV = DATA_DIR / 'deepalgpro_test_cleaned.csv'
POSITIVES_SPLITB_CSV = DATA_DIR / 'positives_splitB.csv'
BASELINE_CHECKPOINT_PATH = RUNTIME_MODELS_DIR / 'baseline_frozen_esm2.pt'
TRAIN_SS3_PATH = SS3_DIR / 'deepalgpro_train_ss3_structured.json.gz'
TEST_SS3_PATH = SS3_DIR / 'deepalgpro_test_ss3_structured.json.gz'
TRAIN_RSA_PATH = DATA_DIR / 'rsa' / 'deepalgpro_train_rsa.json.gz'
SS3_RESULTS_DIR = RESULTS_DIR / 'ss3_regularization'
SS3_RESULTS_DIR.mkdir(parents=True, exist_ok=True)
SS3_SWEEP_CSV = SS3_RESULTS_DIR / 'sweep_summary.csv'

for required_path in [
    TRAIN_CSV, TEST_CSV, TRAIN_SS3_PATH, TEST_SS3_PATH,
    POSITIVES_SPLITB_CSV, BASELINE_CHECKPOINT_PATH,
]:
    if not required_path.exists():
        raise FileNotFoundError(f'Missing required file: {required_path}')

# λ=0 (unregularized baseline) is skipped — already present in the RSA sweep
# and identical across constraints. It appears in Section C for comparison.
SS3_CONFIG = RSARegularizationConfig(
    lambda_cls=1.0,
    lambda_rsa_values=(0.1, 0.5, 1.0, 5.0),
    add_special_tokens=False,
    feature_key='ss3_structured',
)

seed_everything(RANDOM_STATE)
DEVICE = 'cuda' if torch.cuda.is_available() else ('mps' if torch.backends.mps.is_available() else 'cpu')
print(f'Device: {DEVICE}')
print(f'Feature: {SS3_CONFIG.feature_key}  (1.0=H/E structured, 0.0=C coil)')
print(f'λ values: {SS3_CONFIG.lambda_rsa_values}')
print(f'Output dir: {SS3_RESULTS_DIR}')

Device: cuda
Feature: ss3_structured  (1.0=H/E structured, 0.0=C coil)
λ values: (0.1, 0.5, 1.0, 5.0)
Output dir: /content/drive/MyDrive/XAllergen2.0/results/ss3_regularization

In [5]:
ss3_train_df = pd.read_csv(TRAIN_CSV).copy()
ss3_test_df = pd.read_csv(TEST_CSV).copy()
for df in [ss3_train_df, ss3_test_df]:
    df['sequence_id'] = df['sequence_id'].astype(str).str.strip()
    df['sequence'] = df['sequence'].astype(str).str.strip().str.upper()
    df['label'] = df['label'].astype(int)

# rsa_min/rsa_max reflect the binary SS3-structured indicator (0.0 or 1.0)
display(inspect_rsa_inputs(
    train_rsa_path=TRAIN_SS3_PATH,
    test_rsa_path=TEST_SS3_PATH,
    train_frame=ss3_train_df,
    test_frame=ss3_test_df,
))

,path,format,compressed,n_sequences,rsa_min,rsa_max,rsa_in_unit_interval,min_length,max_length,expected_sequences,missing_sequences,extra_sequences,exact_id_match
0,/content/XAllergen2.0/data/ss3/deepalgpro_trai...,precomputed_rsa_json,True,5551,0.0,1.0,True,11,999,5551,0,0,True
1,/content/XAllergen2.0/data/ss3/deepalgpro_test...,precomputed_rsa_json,True,1377,0.0,1.0,True,11,979,1377,0,0,True

In [6]:
seed_everything(RANDOM_STATE)
ss3_train_split_df, ss3_val_split_df = train_test_split(
    ss3_train_df,
    test_size=0.1,
    random_state=RANDOM_STATE,
    stratify=ss3_train_df['label'],
)
ss3_train_split_df = ss3_train_split_df.reset_index(drop=True).copy()
ss3_val_split_df = ss3_val_split_df.reset_index(drop=True).copy()

print(f'Train: {len(ss3_train_split_df):,} | Val: {len(ss3_val_split_df):,} | Test: {len(ss3_test_df):,}')

Train: 4,995 | Val: 556 | Test: 1,377

In [7]:
ss3_train_lookup, ss3_test_lookup, ss3_lookup_summary = load_rsa_lookup_dicts(
    train_rsa_path=TRAIN_SS3_PATH,
    test_rsa_path=TEST_SS3_PATH,
    train_frame=ss3_train_df,
    test_frame=ss3_test_df,
    add_special_tokens=SS3_CONFIG.add_special_tokens,
)
display(pd.DataFrame([ss3_lookup_summary['train'], ss3_lookup_summary['test']]))

,path,format,compressed,n_expected_sequences,n_parsed_sequences,n_missing_sequences,n_extra_sequences,n_length_mismatches,missing_sequence_ids,extra_sequence_ids,length_mismatches,add_special_tokens
0,/content/XAllergen2.0/data/ss3/deepalgpro_trai...,precomputed_rsa_json,True,5551,5551,0,0,0,[],[],[],False
1,/content/XAllergen2.0/data/ss3/deepalgpro_test...,precomputed_rsa_json,True,1377,1377,0,0,0,[],[],[],False

In [8]:
import gzip, json

if not TRAIN_RSA_PATH.exists():
    print(f'Skipping RSA-vs-SS3 correlation; missing optional file: {TRAIN_RSA_PATH}')
else:
    with gzip.open(TRAIN_RSA_PATH, 'rt') as f:
        rsa_train_lookup_raw = json.load(f)

    # Pearson r between RSA and SS3-structured pooled over all train residues.
    # Low |r| means the two constraints carry complementary signal.
    compute_rsa_ss3_structured_correlation(rsa_train_lookup_raw, ss3_train_lookup)

Skipping RSA-vs-SS3 correlation; missing optional file: /content/XAllergen2.0/data/rsa/deepalgpro_train_rsa.json.gz

In [9]:
ss3_sweep_df = run_lambda_rsa_sweep(
    config=SS3_CONFIG,
    train_split_df=ss3_train_split_df,
    val_split_df=ss3_val_split_df,
    test_df=ss3_test_df,
    train_rsa_lookup=ss3_train_lookup,
    test_rsa_lookup=ss3_test_lookup,
    positives_splitb_csv=POSITIVES_SPLITB_CSV,
    output_dir=SS3_RESULTS_DIR,
    device=DEVICE,
).loc[:, [
    'lambda_rsa', 'epoch',
    'val_auroc', 'val_precision', 'val_recall', 'val_f1', 'val_mcc', 'val_accuracy',
    'test_auroc', 'test_precision', 'test_recall', 'test_f1', 'test_mcc', 'test_accuracy',
    'residue_auroc', 'residue_auprc', 'residue_precision_at_k',
]].copy()
ss3_sweep_df.to_csv(SS3_SWEEP_CSV, index=False)
display(ss3_sweep_df)
print(f'Saved to: {SS3_SWEEP_CSV}')
torch.cuda.empty_cache()

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=0.1:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43261 | train_rsa=0.00417 | train_total=0.43303 | val_cls=0.33749 | val_rsa=0.00385 | val_total=0.33787 | val_auroc=0.94350 | best=1
Epoch   2/30 | train_cls=0.31302 | train_rsa=0.00440 | train_total=0.31346 | val_cls=0.27910 | val_rsa=0.00398 | val_total=0.27950 | val_auroc=0.95716 | best=2
Epoch   3/30 | train_cls=0.27820 | train_rsa=0.00447 | train_total=0.27865 | val_cls=0.27015 | val_rsa=0.00402 | val_total=0.27055 | val_auroc=0.96120 | best=3
Epoch   4/30 | train_cls=0.25634 | train_rsa=0.00451 | train_total=0.25679 | val_cls=0.25019 | val_rsa=0.00405 | val_total=0.25059 | val_auroc=0.96513 | best=4
Epoch   5/30 | train_cls=0.23931 | train_rsa=0.00453 | train_total=0.23976 | val_cls=0.25327 | val_rsa=0.00407 | val_total=0.25368 | val_auroc=0.96280 | best=4
Epoch   6/30 | train_cls=0.22990 | train_rsa=0.00455 | train_total=0.23036 | val_cls=0.23666 | val_rsa=0.00409 | val_total=0.23707 | val_auroc=0.96826 | best=6
Epoch   7/30 | train_cls=0.22005 | train_rsa=0.00455 | train_total=0.22050 | val_cls=0.22320 | val_rsa=0.00413 | val_total=0.22361 | val_auroc=0.97257 | best=7
Epoch   8/30 | train_cls=0.20579 | train_rsa=0.00456 | train_total=0.20625 | val_cls=0.23396 | val_rsa=0.00406 | val_total=0.23437 | val_auroc=0.97086 | best=7
Epoch   9/30 | train_cls=0.19452 | train_rsa=0.00456 | train_total=0.19497 | val_cls=0.20978 | val_rsa=0.00411 | val_total=0.21019 | val_auroc=0.97479 | best=9
Epoch  10/30 | train_cls=0.18543 | train_rsa=0.00455 | train_total=0.18588 | val_cls=0.21147 | val_rsa=0.00410 | val_total=0.21188 | val_auroc=0.97398 | best=9
Epoch  11/30 | train_cls=0.18162 | train_rsa=0.00456 | train_total=0.18208 | val_cls=0.20139 | val_rsa=0.00408 | val_total=0.20180 | val_auroc=0.97618 | best=11
Epoch  12/30 | train_cls=0.17339 | train_rsa=0.00456 | train_total=0.17384 | val_cls=0.21872 | val_rsa=0.00406 | val_total=0.21913 | val_auroc=0.97594 | best=11
Epoch  13/30 | train_cls=0.17167 | train_rsa=0.00456 | train_total=0.17213 | val_cls=0.20620 | val_rsa=0.00409 | val_total=0.20661 | val_auroc=0.97576 | best=11
Epoch  14/30 | train_cls=0.15901 | train_rsa=0.00459 | train_total=0.15947 | val_cls=0.20261 | val_rsa=0.00409 | val_total=0.20302 | val_auroc=0.97582 | best=11
Epoch  15/30 | train_cls=0.16056 | train_rsa=0.00458 | train_total=0.16102 | val_cls=0.20420 | val_rsa=0.00410 | val_total=0.20461 | val_auroc=0.97677 | best=11
Epoch  16/30 | train_cls=0.15074 | train_rsa=0.00458 | train_total=0.15120 | val_cls=0.19628 | val_rsa=0.00410 | val_total=0.19669 | val_auroc=0.97706 | best=16
Epoch  17/30 | train_cls=0.14791 | train_rsa=0.00459 | train_total=0.14837 | val_cls=0.20531 | val_rsa=0.00408 | val_total=0.20572 | val_auroc=0.97740 | best=16
Epoch  18/30 | train_cls=0.14380 | train_rsa=0.00458 | train_total=0.14426 | val_cls=0.20753 | val_rsa=0.00407 | val_total=0.20794 | val_auroc=0.97534 | best=16
Epoch  19/30 | train_cls=0.14165 | train_rsa=0.00458 | train_total=0.14211 | val_cls=0.20111 | val_rsa=0.00411 | val_total=0.20152 | val_auroc=0.97781 | best=16
Epoch  20/30 | train_cls=0.13138 | train_rsa=0.00458 | train_total=0.13184 | val_cls=0.20699 | val_rsa=0.00410 | val_total=0.20740 | val_auroc=0.97532 | best=16
Epoch  21/30 | train_cls=0.12784 | train_rsa=0.00458 | train_total=0.12830 | val_cls=0.19949 | val_rsa=0.00408 | val_total=0.19990 | val_auroc=0.97732 | best=16
Early stopping triggered at epoch 21.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=0.5:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43279 | train_rsa=0.00415 | train_total=0.43486 | val_cls=0.33707 | val_rsa=0.00382 | val_total=0.33898 | val_auroc=0.94346 | best=1
Epoch   2/30 | train_cls=0.31310 | train_rsa=0.00437 | train_total=0.31529 | val_cls=0.27859 | val_rsa=0.00395 | val_total=0.28057 | val_auroc=0.95729 | best=2
Epoch   3/30 | train_cls=0.27838 | train_rsa=0.00444 | train_total=0.28060 | val_cls=0.27045 | val_rsa=0.00399 | val_total=0.27245 | val_auroc=0.96104 | best=3
Epoch   4/30 | train_cls=0.25754 | train_rsa=0.00448 | train_total=0.25978 | val_cls=0.25116 | val_rsa=0.00402 | val_total=0.25317 | val_auroc=0.96495 | best=4
Epoch   5/30 | train_cls=0.23953 | train_rsa=0.00449 | train_total=0.24178 | val_cls=0.25323 | val_rsa=0.00403 | val_total=0.25525 | val_auroc=0.96294 | best=4
Epoch   6/30 | train_cls=0.22963 | train_rsa=0.00451 | train_total=0.23189 | val_cls=0.23590 | val_rsa=0.00404 | val_total=0.23793 | val_auroc=0.96848 | best=6
Epoch   7/30 | train_cls=0.21986 | train_rsa=0.00451 | train_total=0.22211 | val_cls=0.22216 | val_rsa=0.00409 | val_total=0.22421 | val_auroc=0.97294 | best=7
Epoch   8/30 | train_cls=0.20539 | train_rsa=0.00451 | train_total=0.20765 | val_cls=0.23111 | val_rsa=0.00401 | val_total=0.23312 | val_auroc=0.97181 | best=7
Epoch   9/30 | train_cls=0.19451 | train_rsa=0.00451 | train_total=0.19676 | val_cls=0.20785 | val_rsa=0.00406 | val_total=0.20988 | val_auroc=0.97543 | best=9
Epoch  10/30 | train_cls=0.18576 | train_rsa=0.00450 | train_total=0.18801 | val_cls=0.21061 | val_rsa=0.00403 | val_total=0.21262 | val_auroc=0.97402 | best=9
Epoch  11/30 | train_cls=0.18213 | train_rsa=0.00451 | train_total=0.18438 | val_cls=0.19768 | val_rsa=0.00402 | val_total=0.19970 | val_auroc=0.97708 | best=11
Epoch  12/30 | train_cls=0.17315 | train_rsa=0.00450 | train_total=0.17540 | val_cls=0.21727 | val_rsa=0.00399 | val_total=0.21926 | val_auroc=0.97688 | best=11
Epoch  13/30 | train_cls=0.17035 | train_rsa=0.00450 | train_total=0.17260 | val_cls=0.20409 | val_rsa=0.00402 | val_total=0.20610 | val_auroc=0.97639 | best=11
Epoch  14/30 | train_cls=0.15852 | train_rsa=0.00452 | train_total=0.16078 | val_cls=0.19855 | val_rsa=0.00402 | val_total=0.20056 | val_auroc=0.97674 | best=11
Epoch  15/30 | train_cls=0.16051 | train_rsa=0.00451 | train_total=0.16276 | val_cls=0.19749 | val_rsa=0.00404 | val_total=0.19951 | val_auroc=0.97805 | best=11
Epoch  16/30 | train_cls=0.15023 | train_rsa=0.00452 | train_total=0.15248 | val_cls=0.19086 | val_rsa=0.00403 | val_total=0.19287 | val_auroc=0.97815 | best=16
Epoch  17/30 | train_cls=0.14743 | train_rsa=0.00451 | train_total=0.14968 | val_cls=0.20085 | val_rsa=0.00400 | val_total=0.20285 | val_auroc=0.97828 | best=16
Epoch  18/30 | train_cls=0.14397 | train_rsa=0.00451 | train_total=0.14623 | val_cls=0.20232 | val_rsa=0.00401 | val_total=0.20433 | val_auroc=0.97659 | best=16
Epoch  19/30 | train_cls=0.14071 | train_rsa=0.00451 | train_total=0.14297 | val_cls=0.19928 | val_rsa=0.00404 | val_total=0.20131 | val_auroc=0.97845 | best=16
Epoch  20/30 | train_cls=0.13095 | train_rsa=0.00452 | train_total=0.13321 | val_cls=0.19926 | val_rsa=0.00402 | val_total=0.20127 | val_auroc=0.97709 | best=16
Epoch  21/30 | train_cls=0.12638 | train_rsa=0.00451 | train_total=0.12863 | val_cls=0.18934 | val_rsa=0.00400 | val_total=0.19134 | val_auroc=0.97933 | best=21
Epoch  22/30 | train_cls=0.12647 | train_rsa=0.00451 | train_total=0.12872 | val_cls=0.20139 | val_rsa=0.00401 | val_total=0.20340 | val_auroc=0.97703 | best=21
Epoch  23/30 | train_cls=0.12305 | train_rsa=0.00451 | train_total=0.12531 | val_cls=0.20101 | val_rsa=0.00401 | val_total=0.20302 | val_auroc=0.97851 | best=21
Epoch  24/30 | train_cls=0.11784 | train_rsa=0.00450 | train_total=0.12009 | val_cls=0.19029 | val_rsa=0.00402 | val_total=0.19230 | val_auroc=0.97876 | best=21
Epoch  25/30 | train_cls=0.11610 | train_rsa=0.00451 | train_total=0.11835 | val_cls=0.19650 | val_rsa=0.00399 | val_total=0.19849 | val_auroc=0.97926 | best=21
Epoch  26/30 | train_cls=0.10854 | train_rsa=0.00451 | train_total=0.11079 | val_cls=0.20000 | val_rsa=0.00402 | val_total=0.20201 | val_auroc=0.97923 | best=21
Early stopping triggered at epoch 26.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=1:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43315 | train_rsa=0.00412 | train_total=0.43727 | val_cls=0.33757 | val_rsa=0.00378 | val_total=0.34135 | val_auroc=0.94328 | best=1
Epoch   2/30 | train_cls=0.31339 | train_rsa=0.00433 | train_total=0.31772 | val_cls=0.27944 | val_rsa=0.00391 | val_total=0.28335 | val_auroc=0.95717 | best=2
Epoch   3/30 | train_cls=0.27908 | train_rsa=0.00440 | train_total=0.28347 | val_cls=0.27100 | val_rsa=0.00395 | val_total=0.27495 | val_auroc=0.96101 | best=3
Epoch   4/30 | train_cls=0.25799 | train_rsa=0.00443 | train_total=0.26242 | val_cls=0.25084 | val_rsa=0.00396 | val_total=0.25480 | val_auroc=0.96478 | best=4
Epoch   5/30 | train_cls=0.24018 | train_rsa=0.00444 | train_total=0.24462 | val_cls=0.25122 | val_rsa=0.00397 | val_total=0.25520 | val_auroc=0.96334 | best=4
Epoch   6/30 | train_cls=0.22969 | train_rsa=0.00445 | train_total=0.23414 | val_cls=0.23536 | val_rsa=0.00399 | val_total=0.23935 | val_auroc=0.96875 | best=6
Epoch   7/30 | train_cls=0.22081 | train_rsa=0.00444 | train_total=0.22525 | val_cls=0.22152 | val_rsa=0.00401 | val_total=0.22553 | val_auroc=0.97262 | best=7
Epoch   8/30 | train_cls=0.20646 | train_rsa=0.00444 | train_total=0.21091 | val_cls=0.23170 | val_rsa=0.00394 | val_total=0.23564 | val_auroc=0.97212 | best=7
Epoch   9/30 | train_cls=0.19562 | train_rsa=0.00444 | train_total=0.20006 | val_cls=0.20710 | val_rsa=0.00398 | val_total=0.21109 | val_auroc=0.97537 | best=9
Epoch  10/30 | train_cls=0.18689 | train_rsa=0.00443 | train_total=0.19131 | val_cls=0.20754 | val_rsa=0.00396 | val_total=0.21151 | val_auroc=0.97471 | best=9
Epoch  11/30 | train_cls=0.18124 | train_rsa=0.00443 | train_total=0.18567 | val_cls=0.19651 | val_rsa=0.00394 | val_total=0.20046 | val_auroc=0.97743 | best=11
Epoch  12/30 | train_cls=0.17361 | train_rsa=0.00442 | train_total=0.17804 | val_cls=0.21071 | val_rsa=0.00391 | val_total=0.21463 | val_auroc=0.97756 | best=11
Epoch  13/30 | train_cls=0.17141 | train_rsa=0.00441 | train_total=0.17582 | val_cls=0.20008 | val_rsa=0.00394 | val_total=0.20401 | val_auroc=0.97737 | best=11
Epoch  14/30 | train_cls=0.15911 | train_rsa=0.00443 | train_total=0.16354 | val_cls=0.19558 | val_rsa=0.00393 | val_total=0.19951 | val_auroc=0.97769 | best=11
Epoch  15/30 | train_cls=0.16048 | train_rsa=0.00443 | train_total=0.16491 | val_cls=0.19733 | val_rsa=0.00395 | val_total=0.20128 | val_auroc=0.97846 | best=11
Epoch  16/30 | train_cls=0.15010 | train_rsa=0.00444 | train_total=0.15453 | val_cls=0.18785 | val_rsa=0.00395 | val_total=0.19180 | val_auroc=0.97888 | best=16
Epoch  17/30 | train_cls=0.14749 | train_rsa=0.00443 | train_total=0.15191 | val_cls=0.19753 | val_rsa=0.00391 | val_total=0.20143 | val_auroc=0.97916 | best=16
Epoch  18/30 | train_cls=0.14324 | train_rsa=0.00442 | train_total=0.14765 | val_cls=0.19773 | val_rsa=0.00391 | val_total=0.20164 | val_auroc=0.97762 | best=16
Epoch  19/30 | train_cls=0.14185 | train_rsa=0.00441 | train_total=0.14626 | val_cls=0.18886 | val_rsa=0.00395 | val_total=0.19281 | val_auroc=0.97983 | best=16
Epoch  20/30 | train_cls=0.13024 | train_rsa=0.00442 | train_total=0.13467 | val_cls=0.19309 | val_rsa=0.00393 | val_total=0.19703 | val_auroc=0.97877 | best=16
Epoch  21/30 | train_cls=0.12756 | train_rsa=0.00441 | train_total=0.13197 | val_cls=0.18683 | val_rsa=0.00390 | val_total=0.19073 | val_auroc=0.97999 | best=21
Epoch  22/30 | train_cls=0.12701 | train_rsa=0.00441 | train_total=0.13142 | val_cls=0.19887 | val_rsa=0.00391 | val_total=0.20278 | val_auroc=0.97770 | best=21
Epoch  23/30 | train_cls=0.12388 | train_rsa=0.00441 | train_total=0.12829 | val_cls=0.20027 | val_rsa=0.00390 | val_total=0.20418 | val_auroc=0.97868 | best=21
Epoch  24/30 | train_cls=0.11689 | train_rsa=0.00440 | train_total=0.12129 | val_cls=0.18692 | val_rsa=0.00390 | val_total=0.19082 | val_auroc=0.97978 | best=21
Epoch  25/30 | train_cls=0.11527 | train_rsa=0.00442 | train_total=0.11969 | val_cls=0.19559 | val_rsa=0.00389 | val_total=0.19948 | val_auroc=0.97942 | best=21
Epoch  26/30 | train_cls=0.10934 | train_rsa=0.00440 | train_total=0.11374 | val_cls=0.19855 | val_rsa=0.00392 | val_total=0.20247 | val_auroc=0.98027 | best=21
Early stopping triggered at epoch 26.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=5:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43514 | train_rsa=0.00391 | train_total=0.45468 | val_cls=0.34143 | val_rsa=0.00347 | val_total=0.35880 | val_auroc=0.94219 | best=1
Epoch   2/30 | train_cls=0.31324 | train_rsa=0.00399 | train_total=0.33317 | val_cls=0.28080 | val_rsa=0.00350 | val_total=0.29831 | val_auroc=0.95777 | best=2
Epoch   3/30 | train_cls=0.27667 | train_rsa=0.00397 | train_total=0.29652 | val_cls=0.27676 | val_rsa=0.00347 | val_total=0.29413 | val_auroc=0.96022 | best=3
Epoch   4/30 | train_cls=0.25558 | train_rsa=0.00394 | train_total=0.27527 | val_cls=0.25152 | val_rsa=0.00342 | val_total=0.26863 | val_auroc=0.96491 | best=4
Epoch   5/30 | train_cls=0.23834 | train_rsa=0.00388 | train_total=0.25775 | val_cls=0.25109 | val_rsa=0.00340 | val_total=0.26808 | val_auroc=0.96394 | best=4
Epoch   6/30 | train_cls=0.22732 | train_rsa=0.00389 | train_total=0.24679 | val_cls=0.23302 | val_rsa=0.00339 | val_total=0.24995 | val_auroc=0.96861 | best=6
Epoch   7/30 | train_cls=0.21834 | train_rsa=0.00384 | train_total=0.23752 | val_cls=0.22245 | val_rsa=0.00336 | val_total=0.23924 | val_auroc=0.97240 | best=7
Epoch   8/30 | train_cls=0.20391 | train_rsa=0.00380 | train_total=0.22294 | val_cls=0.22866 | val_rsa=0.00329 | val_total=0.24509 | val_auroc=0.97295 | best=7
Epoch   9/30 | train_cls=0.19426 | train_rsa=0.00378 | train_total=0.21313 | val_cls=0.20102 | val_rsa=0.00329 | val_total=0.21747 | val_auroc=0.97690 | best=9
Epoch  10/30 | train_cls=0.18346 | train_rsa=0.00374 | train_total=0.20214 | val_cls=0.20218 | val_rsa=0.00324 | val_total=0.21837 | val_auroc=0.97613 | best=9
Epoch  11/30 | train_cls=0.17973 | train_rsa=0.00371 | train_total=0.19827 | val_cls=0.18895 | val_rsa=0.00321 | val_total=0.20500 | val_auroc=0.97872 | best=11
Epoch  12/30 | train_cls=0.17164 | train_rsa=0.00369 | train_total=0.19010 | val_cls=0.19614 | val_rsa=0.00316 | val_total=0.21194 | val_auroc=0.97974 | best=11
Epoch  13/30 | train_cls=0.16709 | train_rsa=0.00367 | train_total=0.18544 | val_cls=0.19454 | val_rsa=0.00315 | val_total=0.21027 | val_auroc=0.97904 | best=11
Epoch  14/30 | train_cls=0.15592 | train_rsa=0.00366 | train_total=0.17420 | val_cls=0.18764 | val_rsa=0.00314 | val_total=0.20333 | val_auroc=0.97965 | best=14
Epoch  15/30 | train_cls=0.15661 | train_rsa=0.00365 | train_total=0.17485 | val_cls=0.17922 | val_rsa=0.00316 | val_total=0.19500 | val_auroc=0.98222 | best=15
Epoch  16/30 | train_cls=0.14610 | train_rsa=0.00363 | train_total=0.16425 | val_cls=0.17747 | val_rsa=0.00311 | val_total=0.19301 | val_auroc=0.98161 | best=16
Epoch  17/30 | train_cls=0.14319 | train_rsa=0.00360 | train_total=0.16119 | val_cls=0.18790 | val_rsa=0.00307 | val_total=0.20327 | val_auroc=0.98167 | best=16
Epoch  18/30 | train_cls=0.13907 | train_rsa=0.00358 | train_total=0.15698 | val_cls=0.18914 | val_rsa=0.00307 | val_total=0.20451 | val_auroc=0.98087 | best=16
Epoch  19/30 | train_cls=0.13683 | train_rsa=0.00358 | train_total=0.15471 | val_cls=0.17225 | val_rsa=0.00307 | val_total=0.18758 | val_auroc=0.98319 | best=19
Epoch  20/30 | train_cls=0.12805 | train_rsa=0.00357 | train_total=0.14589 | val_cls=0.17741 | val_rsa=0.00305 | val_total=0.19264 | val_auroc=0.98232 | best=19
Epoch  21/30 | train_cls=0.12354 | train_rsa=0.00355 | train_total=0.14129 | val_cls=0.17180 | val_rsa=0.00300 | val_total=0.18681 | val_auroc=0.98264 | best=19
Epoch  22/30 | train_cls=0.12401 | train_rsa=0.00354 | train_total=0.14172 | val_cls=0.18417 | val_rsa=0.00299 | val_total=0.19913 | val_auroc=0.98119 | best=19
Epoch  23/30 | train_cls=0.11877 | train_rsa=0.00351 | train_total=0.13634 | val_cls=0.18006 | val_rsa=0.00301 | val_total=0.19511 | val_auroc=0.98185 | best=19
Epoch  24/30 | train_cls=0.11485 | train_rsa=0.00352 | train_total=0.13245 | val_cls=0.16225 | val_rsa=0.00305 | val_total=0.17750 | val_auroc=0.98417 | best=24
Epoch  25/30 | train_cls=0.11047 | train_rsa=0.00352 | train_total=0.12809 | val_cls=0.17277 | val_rsa=0.00295 | val_total=0.18754 | val_auroc=0.98389 | best=24
Epoch  26/30 | train_cls=0.10614 | train_rsa=0.00348 | train_total=0.12355 | val_cls=0.17516 | val_rsa=0.00298 | val_total=0.19004 | val_auroc=0.98407 | best=24
Epoch  27/30 | train_cls=0.10563 | train_rsa=0.00347 | train_total=0.12301 | val_cls=0.17830 | val_rsa=0.00297 | val_total=0.19313 | val_auroc=0.98282 | best=24
Epoch  28/30 | train_cls=0.10258 | train_rsa=0.00347 | train_total=0.11995 | val_cls=0.16543 | val_rsa=0.00297 | val_total=0.18029 | val_auroc=0.98461 | best=24
Epoch  29/30 | train_cls=0.09187 | train_rsa=0.00346 | train_total=0.10918 | val_cls=0.16394 | val_rsa=0.00294 | val_total=0.17866 | val_auroc=0.98448 | best=24
Early stopping triggered at epoch 29.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

,lambda_rsa,epoch,val_auroc,val_precision,val_recall,val_f1,val_mcc,val_accuracy,test_auroc,test_precision,test_recall,test_f1,test_mcc,test_accuracy,residue_auroc,residue_auprc,residue_precision_at_k
0,0.1,16,0.977064,0.916667,0.926740,0.921676,0.845353,0.922662,0.968984,0.899425,0.931548,0.915205,0.832067,0.915759,0.4699,0.2537,0.2155
1,0.5,21,0.979329,0.933579,0.926740,0.930147,0.863270,0.931655,0.969759,0.916542,0.915179,0.915860,0.835776,0.917938,0.4732,0.2553,0.2221
2,1.0,21,0.979989,0.933086,0.919414,0.926199,0.856120,0.928058,0.969744,0.919643,0.919643,0.919643,0.843047,0.921569,0.4789,0.2583,0.2267
3,5.0,24,0.984170,0.934545,0.941392,0.937956,0.877697,0.938849,0.968442,0.914831,0.927083,0.920916,0.844621,0.922295,0.5300,0.2863,0.2649

Saved to: /content/drive/MyDrive/XAllergen2.0/results/ss3_regularization/sweep_summary.csv

In [10]:
best_ss3 = ss3_sweep_df.loc[ss3_sweep_df['val_mcc'].idxmax()]
print('=== SS3-structured: best λ by val MCC ===')
print(f'  Best λ       : {best_ss3["lambda_rsa"]}')
print(f'  Val MCC      : {best_ss3["val_mcc"]:.4f}')
print(f'  Test MCC     : {best_ss3["test_mcc"]:.4f}')
print(f'  Test AUROC   : {best_ss3["test_auroc"]:.4f}')
print(f'  Residue AUROC: {best_ss3["residue_auroc"]:.4f}')

=== SS3-structured: best λ by val MCC ===
  Best λ       : 5.0
  Val MCC      : 0.8777
  Test MCC     : 0.8446
  Test AUROC   : 0.9684
  Residue AUROC: 0.5300

---
## Section B — Disorder Regularization Sweep

Tests whether penalising attention on ordered (low-disorder) residues improves allergenicity
classification. The same loss form as Section A, with per-residue disorder score as $f_i$:

$$\mathcal{L} = \lambda_\text{cls}\mathcal{L}_\text{cls} + \lambda_\text{reg} \cdot \frac{1}{L}\sum_i \alpha_i (1 - f_i)$$

where $f_i = 1.0$ for disordered residues and $f_i = 0.0$ for ordered residues.
The $(1 - f_i)$ term is 0 for disordered positions and 1 for ordered positions,
so the loss penalises attention on structured/ordered residues — reflecting that allergen
epitopes tend to localise in flexible, disordered regions.

In [11]:
TRAIN_DISORDER_PATH = DISORDER_DIR / 'deepalgpro_train_disorder.json.gz'
TEST_DISORDER_PATH = DISORDER_DIR / 'deepalgpro_test_disorder.json.gz'
DISORDER_RESULTS_DIR = RESULTS_DIR / 'disorder_regularization'
DISORDER_RESULTS_DIR.mkdir(parents=True, exist_ok=True)
DISORDER_SWEEP_CSV = DISORDER_RESULTS_DIR / 'sweep_summary.csv'

DISORDER_CONFIG = RSARegularizationConfig(
    lambda_cls=1.0,
    lambda_rsa_values=(0.1, 0.5, 1.0, 5.0),
    add_special_tokens=False,
    feature_key='disorder',
)

for required_path in [TRAIN_DISORDER_PATH, TEST_DISORDER_PATH]:
    if not required_path.exists():
        raise FileNotFoundError(f'Missing required file: {required_path}')

seed_everything(RANDOM_STATE)
print(f'Feature: {DISORDER_CONFIG.feature_key}  (1.0=disordered, 0.0=ordered)')
print(f'λ values: {DISORDER_CONFIG.lambda_rsa_values}')
print(f'Output dir: {DISORDER_RESULTS_DIR}')

Feature: disorder  (1.0=disordered, 0.0=ordered)
λ values: (0.1, 0.5, 1.0, 5.0)
Output dir: /content/drive/MyDrive/XAllergen2.0/results/disorder_regularization

In [12]:
display(inspect_rsa_inputs(
    train_rsa_path=TRAIN_DISORDER_PATH,
    test_rsa_path=TEST_DISORDER_PATH,
    train_frame=ss3_train_df,
    test_frame=ss3_test_df,
))

,path,format,compressed,n_sequences,rsa_min,rsa_max,rsa_in_unit_interval,min_length,max_length,expected_sequences,missing_sequences,extra_sequences,exact_id_match
0,/content/XAllergen2.0/data/disorder/deepalgpro...,precomputed_rsa_json,True,5551,0.000007,0.999941,True,11,999,5551,0,0,True
1,/content/XAllergen2.0/data/disorder/deepalgpro...,precomputed_rsa_json,True,1377,0.000008,0.999861,True,11,979,1377,0,0,True

In [13]:
disorder_train_lookup, disorder_test_lookup, disorder_lookup_summary = load_rsa_lookup_dicts(
    train_rsa_path=TRAIN_DISORDER_PATH,
    test_rsa_path=TEST_DISORDER_PATH,
    train_frame=ss3_train_df,
    test_frame=ss3_test_df,
    add_special_tokens=DISORDER_CONFIG.add_special_tokens,
)
display(pd.DataFrame([disorder_lookup_summary['train'], disorder_lookup_summary['test']]))

,path,format,compressed,n_expected_sequences,n_parsed_sequences,n_missing_sequences,n_extra_sequences,n_length_mismatches,missing_sequence_ids,extra_sequence_ids,length_mismatches,add_special_tokens
0,/content/XAllergen2.0/data/disorder/deepalgpro...,precomputed_rsa_json,True,5551,5551,0,0,0,[],[],[],False
1,/content/XAllergen2.0/data/disorder/deepalgpro...,precomputed_rsa_json,True,1377,1377,0,0,0,[],[],[],False

In [14]:
disorder_sweep_df = run_lambda_rsa_sweep(
    config=DISORDER_CONFIG,
    train_split_df=ss3_train_split_df,
    val_split_df=ss3_val_split_df,
    test_df=ss3_test_df,
    train_rsa_lookup=disorder_train_lookup,
    test_rsa_lookup=disorder_test_lookup,
    positives_splitb_csv=POSITIVES_SPLITB_CSV,
    output_dir=DISORDER_RESULTS_DIR,
    device=DEVICE,
).loc[:, [
    'lambda_rsa', 'epoch',
    'val_auroc', 'val_precision', 'val_recall', 'val_f1', 'val_mcc', 'val_accuracy',
    'test_auroc', 'test_precision', 'test_recall', 'test_f1', 'test_mcc', 'test_accuracy',
    'residue_auroc', 'residue_auprc', 'residue_precision_at_k',
]].copy()
disorder_sweep_df.to_csv(DISORDER_SWEEP_CSV, index=False)
display(disorder_sweep_df)
print(f'Saved to: {DISORDER_SWEEP_CSV}')
torch.cuda.empty_cache()

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=0.1:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43253 | train_rsa=0.00444 | train_total=0.43297 | val_cls=0.33747 | val_rsa=0.00414 | val_total=0.33788 | val_auroc=0.94358 | best=1
Epoch   2/30 | train_cls=0.31309 | train_rsa=0.00425 | train_total=0.31352 | val_cls=0.27883 | val_rsa=0.00405 | val_total=0.27924 | val_auroc=0.95709 | best=2
Epoch   3/30 | train_cls=0.27857 | train_rsa=0.00420 | train_total=0.27899 | val_cls=0.27024 | val_rsa=0.00399 | val_total=0.27064 | val_auroc=0.96113 | best=3
Epoch   4/30 | train_cls=0.25711 | train_rsa=0.00418 | train_total=0.25753 | val_cls=0.24999 | val_rsa=0.00401 | val_total=0.25039 | val_auroc=0.96517 | best=4
Epoch   5/30 | train_cls=0.24000 | train_rsa=0.00418 | train_total=0.24042 | val_cls=0.25329 | val_rsa=0.00401 | val_total=0.25369 | val_auroc=0.96275 | best=4
Epoch   6/30 | train_cls=0.22976 | train_rsa=0.00416 | train_total=0.23018 | val_cls=0.23695 | val_rsa=0.00398 | val_total=0.23735 | val_auroc=0.96809 | best=6
Epoch   7/30 | train_cls=0.21929 | train_rsa=0.00418 | train_total=0.21971 | val_cls=0.22352 | val_rsa=0.00394 | val_total=0.22392 | val_auroc=0.97251 | best=7
Epoch   8/30 | train_cls=0.20601 | train_rsa=0.00418 | train_total=0.20642 | val_cls=0.23395 | val_rsa=0.00404 | val_total=0.23435 | val_auroc=0.97124 | best=7
Epoch   9/30 | train_cls=0.19487 | train_rsa=0.00419 | train_total=0.19529 | val_cls=0.20921 | val_rsa=0.00397 | val_total=0.20961 | val_auroc=0.97502 | best=9
Epoch  10/30 | train_cls=0.18563 | train_rsa=0.00420 | train_total=0.18605 | val_cls=0.21010 | val_rsa=0.00401 | val_total=0.21050 | val_auroc=0.97432 | best=9
Epoch  11/30 | train_cls=0.18104 | train_rsa=0.00419 | train_total=0.18146 | val_cls=0.20177 | val_rsa=0.00402 | val_total=0.20217 | val_auroc=0.97653 | best=11
Epoch  12/30 | train_cls=0.17308 | train_rsa=0.00420 | train_total=0.17350 | val_cls=0.21719 | val_rsa=0.00407 | val_total=0.21760 | val_auroc=0.97646 | best=11
Epoch  13/30 | train_cls=0.17147 | train_rsa=0.00421 | train_total=0.17189 | val_cls=0.20307 | val_rsa=0.00405 | val_total=0.20347 | val_auroc=0.97671 | best=11
Epoch  14/30 | train_cls=0.15817 | train_rsa=0.00419 | train_total=0.15859 | val_cls=0.20112 | val_rsa=0.00404 | val_total=0.20153 | val_auroc=0.97624 | best=11
Epoch  15/30 | train_cls=0.16025 | train_rsa=0.00420 | train_total=0.16067 | val_cls=0.20184 | val_rsa=0.00402 | val_total=0.20224 | val_auroc=0.97775 | best=11
Epoch  16/30 | train_cls=0.14995 | train_rsa=0.00420 | train_total=0.15037 | val_cls=0.19209 | val_rsa=0.00400 | val_total=0.19249 | val_auroc=0.97796 | best=16
Epoch  17/30 | train_cls=0.14724 | train_rsa=0.00420 | train_total=0.14766 | val_cls=0.20340 | val_rsa=0.00407 | val_total=0.20381 | val_auroc=0.97791 | best=16
Epoch  18/30 | train_cls=0.14461 | train_rsa=0.00420 | train_total=0.14503 | val_cls=0.20202 | val_rsa=0.00406 | val_total=0.20243 | val_auroc=0.97677 | best=16
Epoch  19/30 | train_cls=0.14190 | train_rsa=0.00421 | train_total=0.14232 | val_cls=0.20076 | val_rsa=0.00402 | val_total=0.20116 | val_auroc=0.97805 | best=16
Epoch  20/30 | train_cls=0.13045 | train_rsa=0.00418 | train_total=0.13087 | val_cls=0.20262 | val_rsa=0.00405 | val_total=0.20302 | val_auroc=0.97666 | best=16
Epoch  21/30 | train_cls=0.12658 | train_rsa=0.00419 | train_total=0.12700 | val_cls=0.19512 | val_rsa=0.00406 | val_total=0.19553 | val_auroc=0.97814 | best=16
Early stopping triggered at epoch 21.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=0.5:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43233 | train_rsa=0.00442 | train_total=0.43455 | val_cls=0.33693 | val_rsa=0.00412 | val_total=0.33899 | val_auroc=0.94377 | best=1
Epoch   2/30 | train_cls=0.31296 | train_rsa=0.00424 | train_total=0.31508 | val_cls=0.27872 | val_rsa=0.00404 | val_total=0.28074 | val_auroc=0.95730 | best=2
Epoch   3/30 | train_cls=0.27866 | train_rsa=0.00419 | train_total=0.28075 | val_cls=0.27041 | val_rsa=0.00398 | val_total=0.27240 | val_auroc=0.96134 | best=3
Epoch   4/30 | train_cls=0.25735 | train_rsa=0.00417 | train_total=0.25944 | val_cls=0.24978 | val_rsa=0.00400 | val_total=0.25178 | val_auroc=0.96532 | best=4
Epoch   5/30 | train_cls=0.24041 | train_rsa=0.00417 | train_total=0.24250 | val_cls=0.25356 | val_rsa=0.00400 | val_total=0.25556 | val_auroc=0.96296 | best=4
Epoch   6/30 | train_cls=0.23018 | train_rsa=0.00415 | train_total=0.23225 | val_cls=0.23654 | val_rsa=0.00397 | val_total=0.23853 | val_auroc=0.96842 | best=6
Epoch   7/30 | train_cls=0.22037 | train_rsa=0.00417 | train_total=0.22245 | val_cls=0.22433 | val_rsa=0.00392 | val_total=0.22629 | val_auroc=0.97257 | best=7
Epoch   8/30 | train_cls=0.20557 | train_rsa=0.00416 | train_total=0.20765 | val_cls=0.23291 | val_rsa=0.00403 | val_total=0.23493 | val_auroc=0.97114 | best=7
Epoch   9/30 | train_cls=0.19531 | train_rsa=0.00418 | train_total=0.19740 | val_cls=0.20998 | val_rsa=0.00395 | val_total=0.21196 | val_auroc=0.97438 | best=9
Epoch  10/30 | train_cls=0.18644 | train_rsa=0.00418 | train_total=0.18853 | val_cls=0.21153 | val_rsa=0.00400 | val_total=0.21353 | val_auroc=0.97383 | best=9
Epoch  11/30 | train_cls=0.18218 | train_rsa=0.00418 | train_total=0.18427 | val_cls=0.20167 | val_rsa=0.00400 | val_total=0.20367 | val_auroc=0.97615 | best=11
Epoch  12/30 | train_cls=0.17413 | train_rsa=0.00418 | train_total=0.17623 | val_cls=0.21719 | val_rsa=0.00405 | val_total=0.21922 | val_auroc=0.97626 | best=11
Epoch  13/30 | train_cls=0.17176 | train_rsa=0.00420 | train_total=0.17386 | val_cls=0.20698 | val_rsa=0.00405 | val_total=0.20900 | val_auroc=0.97577 | best=11
Epoch  14/30 | train_cls=0.15802 | train_rsa=0.00418 | train_total=0.16011 | val_cls=0.20098 | val_rsa=0.00404 | val_total=0.20300 | val_auroc=0.97635 | best=11
Epoch  15/30 | train_cls=0.15980 | train_rsa=0.00419 | train_total=0.16189 | val_cls=0.20294 | val_rsa=0.00401 | val_total=0.20494 | val_auroc=0.97691 | best=11
Epoch  16/30 | train_cls=0.15075 | train_rsa=0.00418 | train_total=0.15284 | val_cls=0.19634 | val_rsa=0.00400 | val_total=0.19834 | val_auroc=0.97701 | best=16
Epoch  17/30 | train_cls=0.14847 | train_rsa=0.00418 | train_total=0.15057 | val_cls=0.20292 | val_rsa=0.00405 | val_total=0.20494 | val_auroc=0.97717 | best=16
Epoch  18/30 | train_cls=0.14454 | train_rsa=0.00418 | train_total=0.14663 | val_cls=0.20659 | val_rsa=0.00405 | val_total=0.20862 | val_auroc=0.97567 | best=16
Epoch  19/30 | train_cls=0.14056 | train_rsa=0.00419 | train_total=0.14266 | val_cls=0.20027 | val_rsa=0.00400 | val_total=0.20227 | val_auroc=0.97781 | best=16
Epoch  20/30 | train_cls=0.13138 | train_rsa=0.00416 | train_total=0.13346 | val_cls=0.20814 | val_rsa=0.00403 | val_total=0.21015 | val_auroc=0.97486 | best=16
Epoch  21/30 | train_cls=0.12916 | train_rsa=0.00417 | train_total=0.13125 | val_cls=0.19879 | val_rsa=0.00405 | val_total=0.20082 | val_auroc=0.97754 | best=16
Early stopping triggered at epoch 21.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=1:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43213 | train_rsa=0.00441 | train_total=0.43654 | val_cls=0.33668 | val_rsa=0.00411 | val_total=0.34079 | val_auroc=0.94389 | best=1
Epoch   2/30 | train_cls=0.31286 | train_rsa=0.00422 | train_total=0.31708 | val_cls=0.27864 | val_rsa=0.00402 | val_total=0.28266 | val_auroc=0.95736 | best=2
Epoch   3/30 | train_cls=0.27822 | train_rsa=0.00417 | train_total=0.28239 | val_cls=0.26929 | val_rsa=0.00396 | val_total=0.27325 | val_auroc=0.96120 | best=3
Epoch   4/30 | train_cls=0.25638 | train_rsa=0.00415 | train_total=0.26053 | val_cls=0.24872 | val_rsa=0.00398 | val_total=0.25269 | val_auroc=0.96556 | best=4
Epoch   5/30 | train_cls=0.23891 | train_rsa=0.00415 | train_total=0.24306 | val_cls=0.25141 | val_rsa=0.00398 | val_total=0.25539 | val_auroc=0.96372 | best=4
Epoch   6/30 | train_cls=0.22869 | train_rsa=0.00413 | train_total=0.23282 | val_cls=0.23672 | val_rsa=0.00395 | val_total=0.24067 | val_auroc=0.96852 | best=6
Epoch   7/30 | train_cls=0.21910 | train_rsa=0.00415 | train_total=0.22325 | val_cls=0.22191 | val_rsa=0.00391 | val_total=0.22581 | val_auroc=0.97296 | best=7
Epoch   8/30 | train_cls=0.20478 | train_rsa=0.00414 | train_total=0.20892 | val_cls=0.23155 | val_rsa=0.00402 | val_total=0.23557 | val_auroc=0.97159 | best=7
Epoch   9/30 | train_cls=0.19344 | train_rsa=0.00415 | train_total=0.19760 | val_cls=0.20901 | val_rsa=0.00393 | val_total=0.21293 | val_auroc=0.97489 | best=9
Epoch  10/30 | train_cls=0.18494 | train_rsa=0.00416 | train_total=0.18911 | val_cls=0.21174 | val_rsa=0.00397 | val_total=0.21571 | val_auroc=0.97409 | best=9
Epoch  11/30 | train_cls=0.18081 | train_rsa=0.00415 | train_total=0.18497 | val_cls=0.20094 | val_rsa=0.00398 | val_total=0.20492 | val_auroc=0.97615 | best=11
Epoch  12/30 | train_cls=0.17159 | train_rsa=0.00416 | train_total=0.17575 | val_cls=0.21783 | val_rsa=0.00403 | val_total=0.22185 | val_auroc=0.97593 | best=11
Epoch  13/30 | train_cls=0.17044 | train_rsa=0.00418 | train_total=0.17462 | val_cls=0.20559 | val_rsa=0.00402 | val_total=0.20961 | val_auroc=0.97603 | best=11
Epoch  14/30 | train_cls=0.15720 | train_rsa=0.00416 | train_total=0.16136 | val_cls=0.20182 | val_rsa=0.00402 | val_total=0.20584 | val_auroc=0.97593 | best=11
Epoch  15/30 | train_cls=0.15894 | train_rsa=0.00417 | train_total=0.16311 | val_cls=0.20388 | val_rsa=0.00399 | val_total=0.20787 | val_auroc=0.97678 | best=11
Epoch  16/30 | train_cls=0.14908 | train_rsa=0.00417 | train_total=0.15325 | val_cls=0.19675 | val_rsa=0.00397 | val_total=0.20072 | val_auroc=0.97693 | best=16
Epoch  17/30 | train_cls=0.14709 | train_rsa=0.00416 | train_total=0.15126 | val_cls=0.20519 | val_rsa=0.00405 | val_total=0.20924 | val_auroc=0.97709 | best=16
Epoch  18/30 | train_cls=0.14420 | train_rsa=0.00417 | train_total=0.14836 | val_cls=0.20690 | val_rsa=0.00403 | val_total=0.21093 | val_auroc=0.97556 | best=16
Epoch  19/30 | train_cls=0.14028 | train_rsa=0.00417 | train_total=0.14444 | val_cls=0.20293 | val_rsa=0.00400 | val_total=0.20692 | val_auroc=0.97775 | best=16
Epoch  20/30 | train_cls=0.13139 | train_rsa=0.00415 | train_total=0.13554 | val_cls=0.20215 | val_rsa=0.00401 | val_total=0.20617 | val_auroc=0.97633 | best=16
Epoch  21/30 | train_cls=0.12653 | train_rsa=0.00416 | train_total=0.13068 | val_cls=0.19621 | val_rsa=0.00402 | val_total=0.20023 | val_auroc=0.97815 | best=16
Early stopping triggered at epoch 21.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=5:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43058 | train_rsa=0.00426 | train_total=0.45186 | val_cls=0.33536 | val_rsa=0.00394 | val_total=0.35504 | val_auroc=0.94390 | best=1
Epoch   2/30 | train_cls=0.31430 | train_rsa=0.00402 | train_total=0.33441 | val_cls=0.27817 | val_rsa=0.00386 | val_total=0.29746 | val_auroc=0.95703 | best=2
Epoch   3/30 | train_cls=0.28032 | train_rsa=0.00397 | train_total=0.30017 | val_cls=0.27305 | val_rsa=0.00379 | val_total=0.29201 | val_auroc=0.95977 | best=3
Epoch   4/30 | train_cls=0.26033 | train_rsa=0.00398 | train_total=0.28021 | val_cls=0.25145 | val_rsa=0.00378 | val_total=0.27037 | val_auroc=0.96478 | best=4
Epoch   5/30 | train_cls=0.24247 | train_rsa=0.00397 | train_total=0.26233 | val_cls=0.25512 | val_rsa=0.00382 | val_total=0.27424 | val_auroc=0.96236 | best=4
Epoch   6/30 | train_cls=0.23228 | train_rsa=0.00395 | train_total=0.25205 | val_cls=0.23959 | val_rsa=0.00376 | val_total=0.25840 | val_auroc=0.96842 | best=6
Epoch   7/30 | train_cls=0.22225 | train_rsa=0.00396 | train_total=0.24205 | val_cls=0.22489 | val_rsa=0.00368 | val_total=0.24329 | val_auroc=0.97234 | best=7
Epoch   8/30 | train_cls=0.20779 | train_rsa=0.00396 | train_total=0.22759 | val_cls=0.23371 | val_rsa=0.00384 | val_total=0.25291 | val_auroc=0.97134 | best=7
Epoch   9/30 | train_cls=0.19607 | train_rsa=0.00397 | train_total=0.21591 | val_cls=0.20899 | val_rsa=0.00373 | val_total=0.22763 | val_auroc=0.97453 | best=9
Epoch  10/30 | train_cls=0.18939 | train_rsa=0.00398 | train_total=0.20929 | val_cls=0.20903 | val_rsa=0.00377 | val_total=0.22790 | val_auroc=0.97462 | best=9
Epoch  11/30 | train_cls=0.18354 | train_rsa=0.00395 | train_total=0.20331 | val_cls=0.20123 | val_rsa=0.00379 | val_total=0.22018 | val_auroc=0.97660 | best=11
Epoch  12/30 | train_cls=0.17643 | train_rsa=0.00397 | train_total=0.19626 | val_cls=0.21463 | val_rsa=0.00384 | val_total=0.23381 | val_auroc=0.97691 | best=11
Epoch  13/30 | train_cls=0.17094 | train_rsa=0.00397 | train_total=0.19081 | val_cls=0.20363 | val_rsa=0.00383 | val_total=0.22279 | val_auroc=0.97642 | best=11
Epoch  14/30 | train_cls=0.16157 | train_rsa=0.00396 | train_total=0.18135 | val_cls=0.20080 | val_rsa=0.00381 | val_total=0.21985 | val_auroc=0.97620 | best=11
Epoch  15/30 | train_cls=0.16132 | train_rsa=0.00396 | train_total=0.18111 | val_cls=0.19764 | val_rsa=0.00379 | val_total=0.21659 | val_auroc=0.97775 | best=15
Epoch  16/30 | train_cls=0.15294 | train_rsa=0.00397 | train_total=0.17280 | val_cls=0.19413 | val_rsa=0.00375 | val_total=0.21287 | val_auroc=0.97766 | best=16
Epoch  17/30 | train_cls=0.14947 | train_rsa=0.00396 | train_total=0.16926 | val_cls=0.20406 | val_rsa=0.00383 | val_total=0.22323 | val_auroc=0.97798 | best=16
Epoch  18/30 | train_cls=0.14516 | train_rsa=0.00395 | train_total=0.16490 | val_cls=0.20804 | val_rsa=0.00383 | val_total=0.22719 | val_auroc=0.97517 | best=16
Epoch  19/30 | train_cls=0.14422 | train_rsa=0.00395 | train_total=0.16398 | val_cls=0.20025 | val_rsa=0.00378 | val_total=0.21915 | val_auroc=0.97784 | best=16
Epoch  20/30 | train_cls=0.13439 | train_rsa=0.00395 | train_total=0.15413 | val_cls=0.19846 | val_rsa=0.00380 | val_total=0.21746 | val_auroc=0.97775 | best=16
Epoch  21/30 | train_cls=0.12740 | train_rsa=0.00394 | train_total=0.14712 | val_cls=0.19461 | val_rsa=0.00379 | val_total=0.21358 | val_auroc=0.97837 | best=16
Early stopping triggered at epoch 21.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
esm.embeddings.position_ids | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
pooler.dense.bias           | MISSING    |
pooler.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

,lambda_rsa,epoch,val_auroc,val_precision,val_recall,val_f1,val_mcc,val_accuracy,test_auroc,test_precision,test_recall,test_f1,test_mcc,test_accuracy,residue_auroc,residue_auprc,residue_precision_at_k
0,0.1,16,0.977957,0.916968,0.930403,0.923636,0.848999,0.924460,0.969660,0.901004,0.934524,0.917458,0.836475,0.917938,0.4689,0.2534,0.2159
1,0.5,16,0.977012,0.923358,0.926740,0.925046,0.852485,0.926259,0.969637,0.899281,0.930060,0.914411,0.830567,0.915033,0.4680,0.2529,0.2162
2,1.0,16,0.976935,0.916968,0.930403,0.923636,0.848999,0.924460,0.969841,0.901004,0.934524,0.917458,0.836475,0.917938,0.4653,0.2515,0.2168
3,5.0,16,0.977660,0.920290,0.930403,0.925319,0.852549,0.926259,0.969225,0.892045,0.934524,0.912791,0.826694,0.912854,0.4523,0.2448,0.2112

Saved to: /content/drive/MyDrive/XAllergen2.0/results/disorder_regularization/sweep_summary.csv

In [15]:
best_disorder = disorder_sweep_df.loc[disorder_sweep_df['val_mcc'].idxmax()]
print('=== Disorder: best λ by val MCC ===')
print(f'  Best λ       : {best_disorder["lambda_rsa"]}')
print(f'  Val MCC      : {best_disorder["val_mcc"]:.4f}')
print(f'  Test MCC     : {best_disorder["test_mcc"]:.4f}')
print(f'  Test AUROC   : {best_disorder["test_auroc"]:.4f}')
print(f'  Residue AUROC: {best_disorder["residue_auroc"]:.4f}')

=== Disorder: best λ by val MCC ===
  Best λ       : 5.0
  Val MCC      : 0.8525
  Test MCC     : 0.8267
  Test AUROC   : 0.9692
  Residue AUROC: 0.4523

---
## Section C — Comparison Table

- **Baseline (λ=0)** — unregularized model, read from the RSA sweep's λ=0 entry.
- **RSA** — best λ > 0 by val MCC from notebook 12.
- **Disorder** — best λ > 0 by val MCC from Section B above.
- **SS3-structured** — best λ > 0 by val MCC from Section A above.

In [16]:
RSA_SWEEP_CSV = RESULTS_DIR / 'rsa_regularization' / 'sweep_summary.csv'
if not RSA_SWEEP_CSV.exists():
    raise FileNotFoundError(
        f'RSA sweep summary not found at {RSA_SWEEP_CSV}. '
        'Run notebook 12 first and ensure its output CSV is present in the results directory.'
    )

def _row(csv_path, label, select_best=True):
    df = pd.read_csv(csv_path)
    row = df.loc[df['val_mcc'].idxmax()] if select_best else df.loc[df['lambda_rsa'].eq(0.0)].iloc[0]
    return {
        'Constraint': label,
        'Best λ': row['lambda_rsa'],
        'Val MCC': round(float(row['val_mcc']), 4),
        'Test MCC': round(float(row['test_mcc']), 4),
        'Test AUROC': round(float(row['test_auroc']), 4),
        'Residue AUROC': round(float(row['residue_auroc']), 4),
    }

comparison_df = pd.DataFrame([
    _row(RSA_SWEEP_CSV,      'Baseline (λ=0)',  select_best=False),
    _row(RSA_SWEEP_CSV,      'RSA',             select_best=True),
    _row(DISORDER_SWEEP_CSV, 'Disorder',        select_best=True),
    _row(SS3_SWEEP_CSV,      'SS3-structured',  select_best=True),
]).set_index('Constraint')

print('=== Comparison (λ>0 rows selected by val MCC) ===')
display(comparison_df)

=== Comparison (λ>0 rows selected by val MCC) ===

                Best λ  Val MCC  Test MCC  Test AUROC  Residue AUROC
Constraint
Baseline (λ=0)     0.0   0.8454    0.8336      0.9699         0.4677
RSA                0.5   0.8597    0.8474      0.9697         0.4660
Disorder           5.0   0.8525    0.8267      0.9692         0.4523
SS3-structured     5.0   0.8777    0.8446      0.9684         0.5300

In [ ]:
# Shut down the runtime after everything above has finished.
os.kill(os.getpid(), 9)

:

:

: