## Google Colab Setup

This notebook can run either locally from the repo or on Google Colab.

Colab workflow:
- Mount Google Drive and save all trained-model outputs there immediately.
- Download only the exact code, data, and pre-computed structural-feature files needed into `/content/XAllergen2.0`.
- Download a fresh ESM-2 snapshot from Hugging Face.
- Avoid `git clone`, which can be less reliable in hosted notebook runtimes.

Required GitHub-hosted artifacts:
- `models/baseline_frozen_esm2.pt`
- `data/ss3/deepalgpro_train_ss3_structured.json.gz` / `deepalgpro_test_ss3_structured.json.gz`

Section C reads `results/ss3_regularization/sweep_summary.csv` produced by notebook 13  
and `results/rsa_regularization/sweep_summary.csv` produced by notebook 12.  
On Colab these are read from Google Drive; run notebooks 12 and 13 first.

In [2]:
import os
import sys
import urllib.request
from pathlib import Path

IS_COLAB = 'google.colab' in sys.modules or Path('/content').exists()
os.environ['XALLERGEN_RUN_TARGET'] = 'colab' if IS_COLAB else 'local'

if IS_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
    DRIVE_ROOT = Path('/content/drive/MyDrive/XAllergen2.0')
else:
    DRIVE_ROOT = None

if IS_COLAB:
    RUNTIME_ROOT = Path('/content/XAllergen2.0')
else:
    for _candidate in [Path.cwd(), *Path.cwd().parents]:
        if (_candidate / 'src' / 'xallergen').exists():
            RUNTIME_ROOT = _candidate
            break
    else:
        raise FileNotFoundError('Could not locate repo root with src/xallergen')

SRC_DIR              = RUNTIME_ROOT / 'src'
PACKAGE_DIR          = SRC_DIR / 'xallergen'
DATA_DIR             = RUNTIME_ROOT / 'data'
SS3_DIR              = DATA_DIR / 'ss3'
RUNTIME_MODELS_DIR   = RUNTIME_ROOT / 'models'
RUNTIME_RESULTS_DIR  = RUNTIME_ROOT / 'results'
HF_DIR               = RUNTIME_ROOT / 'hf_models' / 'facebook_esm2_t6_8M_UR50D'

if IS_COLAB:
    MODELS_DIR  = DRIVE_ROOT / 'models'
    RESULTS_DIR = DRIVE_ROOT / 'results'
else:
    MODELS_DIR  = RUNTIME_MODELS_DIR
    RESULTS_DIR = RUNTIME_RESULTS_DIR

for path in [
    SRC_DIR, PACKAGE_DIR, DATA_DIR, SS3_DIR,
    RUNTIME_MODELS_DIR, RUNTIME_RESULTS_DIR, MODELS_DIR, RESULTS_DIR, HF_DIR,
]:
    path.mkdir(parents=True, exist_ok=True)

if IS_COLAB:
    from huggingface_hub import snapshot_download

    RAW = 'https://raw.githubusercontent.com/Jeffateth/XAllergen2.0/main'

    package_files = [
        '__init__.py',
        'baseline_notebook_utils.py',
        'baseline_sasa_experiment.py',
        'mtl_epitope_notebook_utils.py',
        'rsa_preprocessing.py',
    ]
    data_files = [
        'deepalgpro_train_cleaned.csv',
        'deepalgpro_test_cleaned.csv',
        'positives_splitB.csv',
    ]
    ss3_files = [
        'deepalgpro_train_ss3_structured.json.gz',
        'deepalgpro_test_ss3_structured.json.gz',
    ]

    download_jobs = []
    download_jobs.extend((f'{RAW}/src/xallergen/{name}', PACKAGE_DIR / name) for name in package_files)
    download_jobs.extend((f'{RAW}/data/{name}', DATA_DIR / name) for name in data_files)
    download_jobs.extend((f'{RAW}/data/ss3/{name}', SS3_DIR / name) for name in ss3_files)
    download_jobs.append((f'{RAW}/models/baseline_frozen_esm2.pt', RUNTIME_MODELS_DIR / 'baseline_frozen_esm2.pt'))

    failed_urls = []
    for url, dst in download_jobs:
        try:
            urllib.request.urlretrieve(url, dst)
        except Exception as exc:
            failed_urls.append((url, str(exc)))

    if failed_urls:
        details = '\n'.join(f'  - {url} -> {err}' for url, err in failed_urls)
        raise RuntimeError('Failed to download required GitHub artifacts:\n' + details)

    fresh_model_path = snapshot_download(
        repo_id='facebook/esm2_t6_8M_UR50D',
        local_dir=HF_DIR,
        local_dir_use_symlinks=False,
        force_download=True,
        resume_download=False,
    )
    os.environ['XALLERGEN_HF_MODEL_DIR'] = str(fresh_model_path)

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

print(f'RUN_TARGET: {os.environ["XALLERGEN_RUN_TARGET"]}')
print(f'Runtime root: {RUNTIME_ROOT}')
print(f'SS3 dir: {SS3_DIR}')
print(f'Output results dir: {RESULTS_DIR}')

Mounted at /content/drive

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:189: UserWarning: The `resume_download` argument is deprecated and ignored in `snapshot_download`. Downloads always resume whenever possible.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py:205: UserWarning: The `local_dir_use_symlinks` argument is deprecated and ignored in `snapshot_download`. Downloading to a local directory does not use symlinks anymore.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 9 files:   0%|          | 0/9 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

RUN_TARGET: colab
Runtime root: /content/XAllergen2.0
SS3 dir: /content/XAllergen2.0/data/ss3
Output results dir: /content/drive/MyDrive/XAllergen2.0/results

# SS3-Structured Regularization — Extended High-λ Sweep

Notebook 13 found that SS3-structured regularization (λ ∈ {0.1, 0.5, 1, 5}) shows monotonically
improving validation MCC and residue AUROC, with the best result at the top of the sweep (λ = 5).
This suggests the optimum may lie at higher λ values.

This notebook extends the sweep to λ ∈ {7, 10, 15, 20} using the same setup.
Results are saved to `results/ss3_high_lambda/` and compared against
the baseline and the earlier sweep in Section B.

In [3]:
import importlib
import sys
from pathlib import Path


def _find_repo_root(start: Path) -> Path:
    for candidate in [start.resolve(), *start.resolve().parents]:
        if (candidate / 'pyproject.toml').exists() or (candidate / 'src' / 'xallergen').exists():
            return candidate
    raise FileNotFoundError('Could not find repo root containing pyproject.toml or src/xallergen')


if 'DATA_DIR' not in globals():
    RUNTIME_ROOT = _find_repo_root(Path.cwd())
    SRC_DIR      = RUNTIME_ROOT / 'src'
    DATA_DIR     = RUNTIME_ROOT / 'data'
    SS3_DIR      = DATA_DIR / 'ss3'
    RUNTIME_MODELS_DIR = RUNTIME_ROOT / 'models'
    RESULTS_DIR  = RUNTIME_ROOT / 'results'
    if str(SRC_DIR) not in sys.path:
        sys.path.insert(0, str(SRC_DIR))

missing_modules = []
for module_name in ('numpy', 'pandas', 'torch', 'IPython', 'sklearn'):
    try:
        importlib.import_module(module_name)
    except ModuleNotFoundError:
        missing_modules.append(module_name)

if missing_modules:
    missing = ', '.join(missing_modules)
    raise ModuleNotFoundError(
        'Notebook dependencies are missing from the active kernel: '
        f'{missing}. Run `make setup` and select `.venv/bin/python` or the '
        '`Python (xallergen2)` kernel before rerunning this cell.'
    )

import pandas as pd
import torch
from IPython.display import display
from sklearn.model_selection import train_test_split

from xallergen.baseline_notebook_utils import RANDOM_STATE, seed_everything
from xallergen.baseline_sasa_experiment import (
    RSARegularizationConfig,
    inspect_rsa_inputs,
    load_rsa_lookup_dicts,
    run_lambda_rsa_sweep,
)

TRAIN_CSV                = DATA_DIR / 'deepalgpro_train_cleaned.csv'
TEST_CSV                 = DATA_DIR / 'deepalgpro_test_cleaned.csv'
POSITIVES_SPLITB_CSV     = DATA_DIR / 'positives_splitB.csv'
BASELINE_CHECKPOINT_PATH = RUNTIME_MODELS_DIR / 'baseline_frozen_esm2.pt'
TRAIN_SS3_PATH           = SS3_DIR / 'deepalgpro_train_ss3_structured.json.gz'
TEST_SS3_PATH            = SS3_DIR / 'deepalgpro_test_ss3_structured.json.gz'

SS3_HIGH_RESULTS_DIR = RESULTS_DIR / 'ss3_high_lambda'
SS3_HIGH_RESULTS_DIR.mkdir(parents=True, exist_ok=True)
SS3_HIGH_SWEEP_CSV = SS3_HIGH_RESULTS_DIR / 'sweep_summary.csv'

for required_path in [
    TRAIN_CSV, TEST_CSV, TRAIN_SS3_PATH, TEST_SS3_PATH,
    POSITIVES_SPLITB_CSV, BASELINE_CHECKPOINT_PATH,
]:
    if not required_path.exists():
        raise FileNotFoundError(f'Missing required file: {required_path}')

SS3_HIGH_CONFIG = RSARegularizationConfig(
    lambda_cls=1.0,
    lambda_rsa_values=(7.0, 10.0, 15.0, 20.0),
    add_special_tokens=False,
    feature_key='ss3_structured',
)

seed_everything(RANDOM_STATE)
DEVICE = 'cuda' if torch.cuda.is_available() else ('mps' if torch.backends.mps.is_available() else 'cpu')
print(f'Device: {DEVICE}')
print(f'Feature: {SS3_HIGH_CONFIG.feature_key}  (1.0=H/E structured, 0.0=C coil)')
print(f'λ values: {SS3_HIGH_CONFIG.lambda_rsa_values}')
print(f'Output dir: {SS3_HIGH_RESULTS_DIR}')

Device: cuda
Feature: ss3_structured  (1.0=H/E structured, 0.0=C coil)
λ values: (7.0, 10.0, 15.0, 20.0)
Output dir: /content/drive/MyDrive/XAllergen2.0/results/ss3_high_lambda

---
## Section A — Data Loading

In [4]:
train_df = pd.read_csv(TRAIN_CSV).copy()
test_df  = pd.read_csv(TEST_CSV).copy()
for df in [train_df, test_df]:
    df['sequence_id'] = df['sequence_id'].astype(str).str.strip()
    df['sequence']    = df['sequence'].astype(str).str.strip().str.upper()
    df['label']       = df['label'].astype(int)

display(inspect_rsa_inputs(
    train_rsa_path=TRAIN_SS3_PATH,
    test_rsa_path=TEST_SS3_PATH,
    train_frame=train_df,
    test_frame=test_df,
))

,path,format,compressed,n_sequences,rsa_min,rsa_max,rsa_in_unit_interval,min_length,max_length,expected_sequences,missing_sequences,extra_sequences,exact_id_match
0,/content/XAllergen2.0/data/ss3/deepalgpro_trai...,precomputed_rsa_json,True,5551,0.0,1.0,True,11,999,5551,0,0,True
1,/content/XAllergen2.0/data/ss3/deepalgpro_test...,precomputed_rsa_json,True,1377,0.0,1.0,True,11,979,1377,0,0,True

In [5]:
seed_everything(RANDOM_STATE)
train_split_df, val_split_df = train_test_split(
    train_df,
    test_size=0.1,
    random_state=RANDOM_STATE,
    stratify=train_df['label'],
)
train_split_df = train_split_df.reset_index(drop=True).copy()
val_split_df   = val_split_df.reset_index(drop=True).copy()

print(f'Train: {len(train_split_df):,} | Val: {len(val_split_df):,} | Test: {len(test_df):,}')

Train: 4,995 | Val: 556 | Test: 1,377

In [6]:
train_lookup, test_lookup, lookup_summary = load_rsa_lookup_dicts(
    train_rsa_path=TRAIN_SS3_PATH,
    test_rsa_path=TEST_SS3_PATH,
    train_frame=train_df,
    test_frame=test_df,
    add_special_tokens=SS3_HIGH_CONFIG.add_special_tokens,
)
display(pd.DataFrame([lookup_summary['train'], lookup_summary['test']]))

,path,format,compressed,n_expected_sequences,n_parsed_sequences,n_missing_sequences,n_extra_sequences,n_length_mismatches,missing_sequence_ids,extra_sequence_ids,length_mismatches,add_special_tokens
0,/content/XAllergen2.0/data/ss3/deepalgpro_trai...,precomputed_rsa_json,True,5551,5551,0,0,0,[],[],[],False
1,/content/XAllergen2.0/data/ss3/deepalgpro_test...,precomputed_rsa_json,True,1377,1377,0,0,0,[],[],[],False

---
## Section B — High-λ Sweep

λ values: **7, 10, 15, 20**.  
Each run starts from the frozen ESM-2 baseline checkpoint and trains with the SS3-structured
penalty on the same train/val split used in notebook 13.

In [7]:
sweep_df = run_lambda_rsa_sweep(
    config=SS3_HIGH_CONFIG,
    train_split_df=train_split_df,
    val_split_df=val_split_df,
    test_df=test_df,
    train_rsa_lookup=train_lookup,
    test_rsa_lookup=test_lookup,
    positives_splitb_csv=POSITIVES_SPLITB_CSV,
    output_dir=SS3_HIGH_RESULTS_DIR,
    device=DEVICE,
).loc[:, [
    'lambda_rsa', 'epoch',
    'val_auroc', 'val_precision', 'val_recall', 'val_f1', 'val_mcc', 'val_accuracy',
    'test_auroc', 'test_precision', 'test_recall', 'test_f1', 'test_mcc', 'test_accuracy',
    'residue_auroc', 'residue_auprc', 'residue_precision_at_k',
]].copy()
sweep_df.to_csv(SS3_HIGH_SWEEP_CSV, index=False)
display(sweep_df)
print(f'Saved to: {SS3_HIGH_SWEEP_CSV}')
torch.cuda.empty_cache()

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=7:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43613 | train_rsa=0.00381 | train_total=0.46282 | val_cls=0.34420 | val_rsa=0.00333 | val_total=0.36748 | val_auroc=0.94131 | best=1
Epoch   2/30 | train_cls=0.31449 | train_rsa=0.00382 | train_total=0.34122 | val_cls=0.28250 | val_rsa=0.00332 | val_total=0.30572 | val_auroc=0.95723 | best=2
Epoch   3/30 | train_cls=0.27684 | train_rsa=0.00377 | train_total=0.30326 | val_cls=0.27679 | val_rsa=0.00326 | val_total=0.29961 | val_auroc=0.95993 | best=3
Epoch   4/30 | train_cls=0.25637 | train_rsa=0.00372 | train_total=0.28240 | val_cls=0.25138 | val_rsa=0.00319 | val_total=0.27373 | val_auroc=0.96487 | best=4
Epoch   5/30 | train_cls=0.23919 | train_rsa=0.00365 | train_total=0.26471 | val_cls=0.25252 | val_rsa=0.00317 | val_total=0.27469 | val_auroc=0.96389 | best=4
Epoch   6/30 | train_cls=0.22773 | train_rsa=0.00366 | train_total=0.25337 | val_cls=0.23397 | val_rsa=0.00314 | val_total=0.25598 | val_auroc=0.96872 | best=6
Epoch   7/30 | train_cls=0.21914 | train_rsa=0.00359 | train_total=0.24430 | val_cls=0.21996 | val_rsa=0.00311 | val_total=0.24175 | val_auroc=0.97308 | best=7
Epoch   8/30 | train_cls=0.20491 | train_rsa=0.00356 | train_total=0.22983 | val_cls=0.22746 | val_rsa=0.00304 | val_total=0.24877 | val_auroc=0.97312 | best=7
Epoch   9/30 | train_cls=0.19408 | train_rsa=0.00352 | train_total=0.21875 | val_cls=0.20018 | val_rsa=0.00304 | val_total=0.22144 | val_auroc=0.97721 | best=9
Epoch  10/30 | train_cls=0.18422 | train_rsa=0.00350 | train_total=0.20869 | val_cls=0.20182 | val_rsa=0.00300 | val_total=0.22279 | val_auroc=0.97637 | best=9
Epoch  11/30 | train_cls=0.17928 | train_rsa=0.00347 | train_total=0.20354 | val_cls=0.18559 | val_rsa=0.00296 | val_total=0.20635 | val_auroc=0.97959 | best=11
Epoch  12/30 | train_cls=0.17362 | train_rsa=0.00344 | train_total=0.19771 | val_cls=0.19237 | val_rsa=0.00292 | val_total=0.21283 | val_auroc=0.97973 | best=11
Epoch  13/30 | train_cls=0.16777 | train_rsa=0.00342 | train_total=0.19173 | val_cls=0.19534 | val_rsa=0.00290 | val_total=0.21561 | val_auroc=0.97889 | best=11
Epoch  14/30 | train_cls=0.15764 | train_rsa=0.00341 | train_total=0.18153 | val_cls=0.18825 | val_rsa=0.00289 | val_total=0.20845 | val_auroc=0.97977 | best=11
Epoch  15/30 | train_cls=0.15796 | train_rsa=0.00339 | train_total=0.18169 | val_cls=0.17644 | val_rsa=0.00291 | val_total=0.19683 | val_auroc=0.98229 | best=15
Epoch  16/30 | train_cls=0.14809 | train_rsa=0.00338 | train_total=0.17177 | val_cls=0.18118 | val_rsa=0.00286 | val_total=0.20119 | val_auroc=0.98049 | best=15
Epoch  17/30 | train_cls=0.14527 | train_rsa=0.00339 | train_total=0.16901 | val_cls=0.18803 | val_rsa=0.00286 | val_total=0.20804 | val_auroc=0.98127 | best=15
Epoch  18/30 | train_cls=0.13966 | train_rsa=0.00335 | train_total=0.16311 | val_cls=0.19023 | val_rsa=0.00284 | val_total=0.21008 | val_auroc=0.98064 | best=15
Epoch  19/30 | train_cls=0.13599 | train_rsa=0.00334 | train_total=0.15938 | val_cls=0.16876 | val_rsa=0.00282 | val_total=0.18853 | val_auroc=0.98326 | best=19
Epoch  20/30 | train_cls=0.12641 | train_rsa=0.00333 | train_total=0.14973 | val_cls=0.17947 | val_rsa=0.00281 | val_total=0.19915 | val_auroc=0.98194 | best=19
Epoch  21/30 | train_cls=0.12121 | train_rsa=0.00331 | train_total=0.14436 | val_cls=0.17177 | val_rsa=0.00279 | val_total=0.19127 | val_auroc=0.98299 | best=19
Epoch  22/30 | train_cls=0.12204 | train_rsa=0.00331 | train_total=0.14518 | val_cls=0.18689 | val_rsa=0.00277 | val_total=0.20626 | val_auroc=0.98069 | best=19
Epoch  23/30 | train_cls=0.11509 | train_rsa=0.00327 | train_total=0.13799 | val_cls=0.17634 | val_rsa=0.00278 | val_total=0.19579 | val_auroc=0.98232 | best=19
Epoch  24/30 | train_cls=0.11244 | train_rsa=0.00328 | train_total=0.13538 | val_cls=0.16748 | val_rsa=0.00280 | val_total=0.18708 | val_auroc=0.98288 | best=24
Epoch  25/30 | train_cls=0.10774 | train_rsa=0.00328 | train_total=0.13067 | val_cls=0.18083 | val_rsa=0.00271 | val_total=0.19978 | val_auroc=0.98232 | best=24
Epoch  26/30 | train_cls=0.10439 | train_rsa=0.00323 | train_total=0.12703 | val_cls=0.18014 | val_rsa=0.00274 | val_total=0.19931 | val_auroc=0.98391 | best=24
Epoch  27/30 | train_cls=0.10472 | train_rsa=0.00323 | train_total=0.12730 | val_cls=0.18894 | val_rsa=0.00272 | val_total=0.20802 | val_auroc=0.98180 | best=24
Epoch  28/30 | train_cls=0.10132 | train_rsa=0.00322 | train_total=0.12387 | val_cls=0.17440 | val_rsa=0.00271 | val_total=0.19340 | val_auroc=0.98396 | best=24
Epoch  29/30 | train_cls=0.09089 | train_rsa=0.00321 | train_total=0.11333 | val_cls=0.17292 | val_rsa=0.00271 | val_total=0.19187 | val_auroc=0.98346 | best=24
Early stopping triggered at epoch 29.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=10:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43677 | train_rsa=0.00369 | train_total=0.47369 | val_cls=0.34884 | val_rsa=0.00313 | val_total=0.38018 | val_auroc=0.94034 | best=1
Epoch   2/30 | train_cls=0.31442 | train_rsa=0.00360 | train_total=0.35043 | val_cls=0.28200 | val_rsa=0.00308 | val_total=0.31284 | val_auroc=0.95740 | best=2
Epoch   3/30 | train_cls=0.27700 | train_rsa=0.00353 | train_total=0.31229 | val_cls=0.27587 | val_rsa=0.00301 | val_total=0.30595 | val_auroc=0.96011 | best=3
Epoch   4/30 | train_cls=0.25546 | train_rsa=0.00345 | train_total=0.29001 | val_cls=0.24926 | val_rsa=0.00293 | val_total=0.27858 | val_auroc=0.96534 | best=4
Epoch   5/30 | train_cls=0.23842 | train_rsa=0.00337 | train_total=0.27213 | val_cls=0.25015 | val_rsa=0.00289 | val_total=0.27906 | val_auroc=0.96470 | best=4
Epoch   6/30 | train_cls=0.22741 | train_rsa=0.00337 | train_total=0.26115 | val_cls=0.23065 | val_rsa=0.00285 | val_total=0.25920 | val_auroc=0.96980 | best=6
Epoch   7/30 | train_cls=0.21870 | train_rsa=0.00330 | train_total=0.25172 | val_cls=0.22300 | val_rsa=0.00282 | val_total=0.25120 | val_auroc=0.97286 | best=7
Epoch   8/30 | train_cls=0.20499 | train_rsa=0.00327 | train_total=0.23771 | val_cls=0.22680 | val_rsa=0.00277 | val_total=0.25451 | val_auroc=0.97257 | best=7
Epoch   9/30 | train_cls=0.19498 | train_rsa=0.00325 | train_total=0.22746 | val_cls=0.20057 | val_rsa=0.00277 | val_total=0.22825 | val_auroc=0.97725 | best=9
Epoch  10/30 | train_cls=0.18526 | train_rsa=0.00322 | train_total=0.21748 | val_cls=0.20501 | val_rsa=0.00272 | val_total=0.23222 | val_auroc=0.97559 | best=9
Epoch  11/30 | train_cls=0.17993 | train_rsa=0.00320 | train_total=0.21190 | val_cls=0.18999 | val_rsa=0.00270 | val_total=0.21701 | val_auroc=0.97851 | best=11
Epoch  12/30 | train_cls=0.17395 | train_rsa=0.00316 | train_total=0.20554 | val_cls=0.19815 | val_rsa=0.00266 | val_total=0.22479 | val_auroc=0.97857 | best=11
Epoch  13/30 | train_cls=0.16765 | train_rsa=0.00315 | train_total=0.19916 | val_cls=0.20323 | val_rsa=0.00263 | val_total=0.22958 | val_auroc=0.97660 | best=11
Epoch  14/30 | train_cls=0.15586 | train_rsa=0.00313 | train_total=0.18719 | val_cls=0.19661 | val_rsa=0.00262 | val_total=0.22284 | val_auroc=0.97789 | best=11
Epoch  15/30 | train_cls=0.15649 | train_rsa=0.00310 | train_total=0.18751 | val_cls=0.18851 | val_rsa=0.00264 | val_total=0.21488 | val_auroc=0.98029 | best=15
Epoch  16/30 | train_cls=0.14780 | train_rsa=0.00310 | train_total=0.17881 | val_cls=0.19056 | val_rsa=0.00258 | val_total=0.21641 | val_auroc=0.97880 | best=15
Epoch  17/30 | train_cls=0.14857 | train_rsa=0.00308 | train_total=0.17933 | val_cls=0.19964 | val_rsa=0.00258 | val_total=0.22545 | val_auroc=0.97893 | best=15
Epoch  18/30 | train_cls=0.14119 | train_rsa=0.00306 | train_total=0.17179 | val_cls=0.20004 | val_rsa=0.00256 | val_total=0.22566 | val_auroc=0.97871 | best=15
Epoch  19/30 | train_cls=0.13587 | train_rsa=0.00305 | train_total=0.16641 | val_cls=0.18203 | val_rsa=0.00255 | val_total=0.20755 | val_auroc=0.98069 | best=19
Epoch  20/30 | train_cls=0.12788 | train_rsa=0.00303 | train_total=0.15822 | val_cls=0.19254 | val_rsa=0.00253 | val_total=0.21789 | val_auroc=0.97898 | best=19
Epoch  21/30 | train_cls=0.12185 | train_rsa=0.00301 | train_total=0.15195 | val_cls=0.18720 | val_rsa=0.00251 | val_total=0.21228 | val_auroc=0.98039 | best=19
Epoch  22/30 | train_cls=0.12384 | train_rsa=0.00301 | train_total=0.15397 | val_cls=0.19498 | val_rsa=0.00250 | val_total=0.21993 | val_auroc=0.97912 | best=19
Epoch  23/30 | train_cls=0.11546 | train_rsa=0.00297 | train_total=0.14513 | val_cls=0.18810 | val_rsa=0.00250 | val_total=0.21314 | val_auroc=0.98035 | best=19
Epoch  24/30 | train_cls=0.11221 | train_rsa=0.00297 | train_total=0.14191 | val_cls=0.18060 | val_rsa=0.00251 | val_total=0.20568 | val_auroc=0.98053 | best=24
Epoch  25/30 | train_cls=0.10645 | train_rsa=0.00297 | train_total=0.13619 | val_cls=0.18768 | val_rsa=0.00244 | val_total=0.21208 | val_auroc=0.98033 | best=24
Epoch  26/30 | train_cls=0.10312 | train_rsa=0.00294 | train_total=0.13250 | val_cls=0.20221 | val_rsa=0.00245 | val_total=0.22671 | val_auroc=0.98095 | best=24
Epoch  27/30 | train_cls=0.10360 | train_rsa=0.00293 | train_total=0.13288 | val_cls=0.19566 | val_rsa=0.00245 | val_total=0.22019 | val_auroc=0.97978 | best=24
Epoch  28/30 | train_cls=0.10041 | train_rsa=0.00293 | train_total=0.12974 | val_cls=0.19368 | val_rsa=0.00245 | val_total=0.21818 | val_auroc=0.98114 | best=24
Epoch  29/30 | train_cls=0.08944 | train_rsa=0.00292 | train_total=0.11862 | val_cls=0.19793 | val_rsa=0.00244 | val_total=0.22231 | val_auroc=0.97992 | best=24
Early stopping triggered at epoch 29.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=15:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43767 | train_rsa=0.00355 | train_total=0.49093 | val_cls=0.35397 | val_rsa=0.00290 | val_total=0.39753 | val_auroc=0.93971 | best=1
Epoch   2/30 | train_cls=0.31484 | train_rsa=0.00333 | train_total=0.36483 | val_cls=0.28220 | val_rsa=0.00281 | val_total=0.32429 | val_auroc=0.95669 | best=2
Epoch   3/30 | train_cls=0.27740 | train_rsa=0.00323 | train_total=0.32590 | val_cls=0.27542 | val_rsa=0.00272 | val_total=0.31617 | val_auroc=0.96000 | best=3
Epoch   4/30 | train_cls=0.25506 | train_rsa=0.00314 | train_total=0.30223 | val_cls=0.24853 | val_rsa=0.00263 | val_total=0.28798 | val_auroc=0.96549 | best=4
Epoch   5/30 | train_cls=0.23866 | train_rsa=0.00305 | train_total=0.28445 | val_cls=0.25341 | val_rsa=0.00258 | val_total=0.29212 | val_auroc=0.96517 | best=4
Epoch   6/30 | train_cls=0.22698 | train_rsa=0.00304 | train_total=0.27255 | val_cls=0.22997 | val_rsa=0.00253 | val_total=0.26785 | val_auroc=0.96984 | best=6
Epoch   7/30 | train_cls=0.22064 | train_rsa=0.00296 | train_total=0.26499 | val_cls=0.22444 | val_rsa=0.00248 | val_total=0.26160 | val_auroc=0.97211 | best=7
Epoch   8/30 | train_cls=0.20765 | train_rsa=0.00292 | train_total=0.25151 | val_cls=0.23131 | val_rsa=0.00244 | val_total=0.26792 | val_auroc=0.97176 | best=7
Epoch   9/30 | train_cls=0.19679 | train_rsa=0.00290 | train_total=0.24026 | val_cls=0.20772 | val_rsa=0.00241 | val_total=0.24393 | val_auroc=0.97524 | best=9
Epoch  10/30 | train_cls=0.18746 | train_rsa=0.00287 | train_total=0.23054 | val_cls=0.21351 | val_rsa=0.00239 | val_total=0.24935 | val_auroc=0.97340 | best=9
Epoch  11/30 | train_cls=0.18155 | train_rsa=0.00286 | train_total=0.22438 | val_cls=0.19578 | val_rsa=0.00237 | val_total=0.23137 | val_auroc=0.97728 | best=11
Epoch  12/30 | train_cls=0.17685 | train_rsa=0.00282 | train_total=0.21912 | val_cls=0.20400 | val_rsa=0.00234 | val_total=0.23916 | val_auroc=0.97769 | best=11
Epoch  13/30 | train_cls=0.16974 | train_rsa=0.00281 | train_total=0.21195 | val_cls=0.21226 | val_rsa=0.00232 | val_total=0.24702 | val_auroc=0.97427 | best=11
Epoch  14/30 | train_cls=0.15864 | train_rsa=0.00279 | train_total=0.20044 | val_cls=0.20053 | val_rsa=0.00231 | val_total=0.23511 | val_auroc=0.97640 | best=11
Epoch  15/30 | train_cls=0.16039 | train_rsa=0.00276 | train_total=0.20172 | val_cls=0.19535 | val_rsa=0.00230 | val_total=0.22986 | val_auroc=0.97880 | best=15
Epoch  16/30 | train_cls=0.15201 | train_rsa=0.00277 | train_total=0.19350 | val_cls=0.20348 | val_rsa=0.00227 | val_total=0.23760 | val_auroc=0.97529 | best=15
Epoch  17/30 | train_cls=0.14829 | train_rsa=0.00273 | train_total=0.18931 | val_cls=0.21469 | val_rsa=0.00227 | val_total=0.24878 | val_auroc=0.97591 | best=15
Epoch  18/30 | train_cls=0.14190 | train_rsa=0.00272 | train_total=0.18277 | val_cls=0.20880 | val_rsa=0.00225 | val_total=0.24255 | val_auroc=0.97809 | best=15
Epoch  19/30 | train_cls=0.13577 | train_rsa=0.00272 | train_total=0.17658 | val_cls=0.19082 | val_rsa=0.00225 | val_total=0.22455 | val_auroc=0.97847 | best=19
Epoch  20/30 | train_cls=0.12745 | train_rsa=0.00271 | train_total=0.16806 | val_cls=0.21051 | val_rsa=0.00224 | val_total=0.24404 | val_auroc=0.97624 | best=19
Epoch  21/30 | train_cls=0.12097 | train_rsa=0.00270 | train_total=0.16153 | val_cls=0.20099 | val_rsa=0.00221 | val_total=0.23419 | val_auroc=0.97687 | best=19
Epoch  22/30 | train_cls=0.12203 | train_rsa=0.00268 | train_total=0.16218 | val_cls=0.21260 | val_rsa=0.00220 | val_total=0.24555 | val_auroc=0.97661 | best=19
Epoch  23/30 | train_cls=0.11453 | train_rsa=0.00265 | train_total=0.15434 | val_cls=0.20022 | val_rsa=0.00220 | val_total=0.23329 | val_auroc=0.97853 | best=19
Epoch  24/30 | train_cls=0.10993 | train_rsa=0.00266 | train_total=0.14984 | val_cls=0.19759 | val_rsa=0.00221 | val_total=0.23076 | val_auroc=0.97721 | best=19
Early stopping triggered at epoch 24.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

lambda_rsa=20:   0%|          | 0/30 [00:00<?, ?epoch/s]

Epoch   1/30 | train_cls=0.43826 | train_rsa=0.00345 | train_total=0.50733 | val_cls=0.35776 | val_rsa=0.00274 | val_total=0.41256 | val_auroc=0.93853 | best=1
Epoch   2/30 | train_cls=0.31589 | train_rsa=0.00314 | train_total=0.37878 | val_cls=0.28228 | val_rsa=0.00262 | val_total=0.33461 | val_auroc=0.95619 | best=2
Epoch   3/30 | train_cls=0.27867 | train_rsa=0.00303 | train_total=0.33929 | val_cls=0.27483 | val_rsa=0.00253 | val_total=0.32537 | val_auroc=0.96010 | best=3
Epoch   4/30 | train_cls=0.25668 | train_rsa=0.00294 | train_total=0.31553 | val_cls=0.24815 | val_rsa=0.00244 | val_total=0.29695 | val_auroc=0.96583 | best=4
Epoch   5/30 | train_cls=0.24022 | train_rsa=0.00285 | train_total=0.29729 | val_cls=0.25337 | val_rsa=0.00239 | val_total=0.30108 | val_auroc=0.96539 | best=4
Epoch   6/30 | train_cls=0.22836 | train_rsa=0.00283 | train_total=0.28489 | val_cls=0.22990 | val_rsa=0.00233 | val_total=0.27656 | val_auroc=0.96993 | best=6
Epoch   7/30 | train_cls=0.22188 | train_rsa=0.00275 | train_total=0.27686 | val_cls=0.22850 | val_rsa=0.00228 | val_total=0.27401 | val_auroc=0.97146 | best=7
Epoch   8/30 | train_cls=0.20947 | train_rsa=0.00271 | train_total=0.26364 | val_cls=0.23076 | val_rsa=0.00224 | val_total=0.27555 | val_auroc=0.97154 | best=7
Epoch   9/30 | train_cls=0.19855 | train_rsa=0.00268 | train_total=0.25214 | val_cls=0.21090 | val_rsa=0.00220 | val_total=0.25495 | val_auroc=0.97402 | best=9
Epoch  10/30 | train_cls=0.18953 | train_rsa=0.00265 | train_total=0.24245 | val_cls=0.22068 | val_rsa=0.00218 | val_total=0.26421 | val_auroc=0.97211 | best=9
Epoch  11/30 | train_cls=0.18281 | train_rsa=0.00262 | train_total=0.23529 | val_cls=0.20069 | val_rsa=0.00216 | val_total=0.24383 | val_auroc=0.97634 | best=11
Epoch  12/30 | train_cls=0.17802 | train_rsa=0.00259 | train_total=0.22982 | val_cls=0.21255 | val_rsa=0.00213 | val_total=0.25519 | val_auroc=0.97503 | best=11
Epoch  13/30 | train_cls=0.17043 | train_rsa=0.00258 | train_total=0.22201 | val_cls=0.22065 | val_rsa=0.00211 | val_total=0.26282 | val_auroc=0.97200 | best=11
Epoch  14/30 | train_cls=0.16032 | train_rsa=0.00255 | train_total=0.21129 | val_cls=0.20972 | val_rsa=0.00209 | val_total=0.25146 | val_auroc=0.97445 | best=11
Epoch  15/30 | train_cls=0.15938 | train_rsa=0.00252 | train_total=0.20976 | val_cls=0.21039 | val_rsa=0.00207 | val_total=0.25171 | val_auroc=0.97492 | best=11
Epoch  16/30 | train_cls=0.15191 | train_rsa=0.00251 | train_total=0.20207 | val_cls=0.21201 | val_rsa=0.00204 | val_total=0.25288 | val_auroc=0.97334 | best=11
Early stopping triggered at epoch 16.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading weights:   0%|          | 0/107 [00:00<?, ?it/s]

EsmModel LOAD REPORT from: /content/XAllergen2.0/hf_models/facebook_esm2_t6_8M_UR50D
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
esm.embeddings.position_ids | UNEXPECTED |
pooler.dense.weight         | MISSING    |
pooler.dense.bias           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Evaluating proteins:   0%|          | 0/61 [00:00<?, ?it/s]

Evaluating proteins: processed 5/61 proteins
Evaluating proteins: processed 10/61 proteins
Evaluating proteins: processed 15/61 proteins
Evaluating proteins: processed 20/61 proteins
Evaluating proteins: processed 25/61 proteins
Evaluating proteins: processed 30/61 proteins
Evaluating proteins: processed 35/61 proteins
Evaluating proteins: processed 40/61 proteins
Evaluating proteins: processed 45/61 proteins
Evaluating proteins: processed 50/61 proteins
Evaluating proteins: processed 55/61 proteins
Evaluating proteins: processed 60/61 proteins
Evaluating proteins: processed 61/61 proteins

,lambda_rsa,epoch,val_auroc,val_precision,val_recall,val_f1,val_mcc,val_accuracy,test_auroc,test_precision,test_recall,test_f1,test_mcc,test_accuracy,residue_auroc,residue_auprc,residue_precision_at_k
0,7.0,24,0.982876,0.934545,0.941392,0.937956,0.877697,0.938849,0.967705,0.902616,0.924107,0.913235,0.828834,0.914306,0.5400,0.2909,0.2693
1,10.0,24,0.980533,0.930403,0.930403,0.930403,0.863265,0.931655,0.964647,0.897547,0.925595,0.911355,0.824667,0.912128,0.5521,0.2988,0.2759
2,15.0,19,0.978475,0.933579,0.926740,0.930147,0.863270,0.931655,0.964273,0.887624,0.928571,0.907636,0.816461,0.907771,0.5551,0.3002,0.2766
3,20.0,11,0.976339,0.926471,0.923077,0.924771,0.852466,0.926259,0.961552,0.881844,0.910714,0.896047,0.794199,0.896877,0.5541,0.3005,0.2839

Saved to: /content/drive/MyDrive/XAllergen2.0/results/ss3_high_lambda/sweep_summary.csv

In [8]:
best = sweep_df.loc[sweep_df['val_mcc'].idxmax()]
print('=== SS3-structured (high λ): best λ by val MCC ===')
print(f'  Best λ       : {best["lambda_rsa"]}')
print(f'  Val MCC      : {best["val_mcc"]:.4f}')
print(f'  Test MCC     : {best["test_mcc"]:.4f}')
print(f'  Test AUROC   : {best["test_auroc"]:.4f}')
print(f'  Residue AUROC: {best["residue_auroc"]:.4f}')

=== SS3-structured (high λ): best λ by val MCC ===
  Best λ       : 7.0
  Val MCC      : 0.8777
  Test MCC     : 0.8288
  Test AUROC   : 0.9677
  Residue AUROC: 0.5400

---
## Section C — Comparison Table

Rows (all selected by best val MCC within each sweep):
- **Baseline (λ=0)** — unregularized model from the RSA sweep (notebook 12)
- **SS3 λ ∈ {0.1–5}** — notebook 13 sweep
- **SS3 λ ∈ {7–20}** — this notebook

In [ ]:
RSA_SWEEP_CSV = RESULTS_DIR / 'rsa_regularization' / 'sweep_summary.csv'
SS3_SWEEP_CSV = RESULTS_DIR / 'ss3_regularization' / 'sweep_summary.csv'

for p in [RSA_SWEEP_CSV, SS3_SWEEP_CSV]:
    if not p.exists():
        raise FileNotFoundError(
            f'{p} not found. Run notebooks 12 and 13 first and ensure their output CSVs are present.'
        )


def _row(csv_path, label, select_best=True):
    df  = pd.read_csv(csv_path)
    row = df.loc[df['val_mcc'].idxmax()] if select_best else df.loc[df['lambda_rsa'].eq(0.0)].iloc[0]
    return {
        'Constraint':           label,
        'Best λ':               row['lambda_rsa'],
        'Val MCC':              round(float(row['val_mcc']),              4),
        'Test MCC':             round(float(row['test_mcc']),             4),
        'Test AUROC':           round(float(row['test_auroc']),           4),
        'Residue AUROC':        round(float(row['residue_auroc']),        4),
        'Residue AUPRC':        round(float(row['residue_auprc']),        4),
        'Residue Prec@k':       round(float(row['residue_precision_at_k']), 4),
    }


def _row_from_df(df, label):
    row = df.loc[df['val_mcc'].idxmax()]
    return {
        'Constraint':           label,
        'Best λ':               row['lambda_rsa'],
        'Val MCC':              round(float(row['val_mcc']),              4),
        'Test MCC':             round(float(row['test_mcc']),             4),
        'Test AUROC':           round(float(row['test_auroc']),           4),
        'Residue AUROC':        round(float(row['residue_auroc']),        4),
        'Residue AUPRC':        round(float(row['residue_auprc']),        4),
        'Residue Prec@k':       round(float(row['residue_precision_at_k']), 4),
    }


comparison_df = pd.DataFrame([
    _row(RSA_SWEEP_CSV,  'Baseline (λ=0)',       select_best=False),
    _row(SS3_SWEEP_CSV,  'SS3 λ∈{0.1–5}',        select_best=True),
    _row_from_df(sweep_df, 'SS3 λ∈{7–20}'),
]).set_index('Constraint')

print('=== SS3-structured: extended λ comparison ===')
display(comparison_df)

=== SS3-structured: extended λ comparison ===

,Best λ,Val MCC,Test MCC,Test AUROC,Residue AUROC,Residue AUPRC,Residue Prec@k
Constraint,,,,,,,
Baseline (λ=0),0.0,0.8454,0.8336,0.9699,0.4677,0.2529,0.2163
SS3 λ∈{0.1–5},5.0,0.8777,0.8446,0.9684,0.5300,0.2863,0.2649
SS3 λ∈{7–20},7.0,0.8777,0.8288,0.9677,0.5400,0.2909,0.2693

:

In [ ]:
# Shut down the Colab runtime to free GPU after training completes.
import os
os.kill(os.getpid(), 9)

:

: